// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'goal': string;
  'issueAwarenessBanner': string;
  'mercury': string;
  'thermo': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
