// This file is automatically generated.
// Please do not change this file!
export const amount: string;
export const material: string;
export const materialCounts: string;
export const spanGrid: string;
export const wide: string;
