// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'classType': string;
  'ornaments': string;
  'record': string;
  'records': string;
  'redeemed': string;
}
export const cssExports: CssExports;
export = cssExports;
