// This file is automatically generated.
// Please do not change this file!
export const classIcon: string;
export const classType: string;
export const ornaments: string;
export const record: string;
export const records: string;
export const redeemed: string;
