// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'faded': string;
  'icon': string;
  'text': string;
}
export const cssExports: CssExports;
export = cssExports;
