// This file is automatically generated.
// Please do not change this file!
export const armorStats: string;
export const asterisk: string;
export const boostedValue: string;
export const dropLevel: string;
export const powerFormula: string;
export const powerStat: string;
export const richTooltipWrapper: string;
export const tier: string;
export const tooltipFootnote: string;
