// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asterisk': string;
  'dropLevel': string;
  'loadoutStats': string;
  'powerFormula': string;
  'powerStat': string;
  'richTooltipWrapper': string;
  'tier': string;
  'tooltipFootnote': string;
}
export const cssExports: CssExports;
export default cssExports;
