// This file is automatically generated.
// Please do not change this file!
export const communityInsightSection: string;
export const currentColumn: string;
export const override: string;
export const unit: string;
export const value: string;
