// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'communityInsightSection': string;
  'currentColumn': string;
  'override': string;
  'unit': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
