// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'barCurrent': string;
  'communityInsightSection': string;
  'graph': string;
}
export const cssExports: CssExports;
export default cssExports;
