// This file is automatically generated.
// Please do not change this file!
export const bar: string;
export const complete: string;
export const progress: string;
export const stat: string;
export const statBars: string;
