// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'complete': string;
  'progress': string;
}
export const cssExports: CssExports;
export default cssExports;
