// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'materialCounts': string;
  'spanGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
