// This file is automatically generated.
// Please do not change this file!
export const boostedValue: string;
export const breakdown: string;
export const breakdownValue: string;
export const icon: string;
export const row: string;
export const title: string;
export const value: string;
