// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boostedValue': string;
  'breakdown': string;
  'breakdownValue': string;
  'icon': string;
  'label': string;
  'row': string;
  'values': string;
}
export const cssExports: CssExports;
export default cssExports;
