// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boostedValue': string;
  'breakdown': string;
  'breakdownValue': string;
  'icon': string;
  'row': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export = cssExports;
