// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'characterStats': string;
  'setBonuses': string;
  'statContainer': string;
  'topRow': string;
  'vaultStats': string;
}
export const cssExports: CssExports;
export = cssExports;
