// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucketCount': string;
  'bucketTag': string;
  'full': string;
}
export const cssExports: CssExports;
export = cssExports;
