// This file is automatically generated.
// Please do not change this file!
export const bucketImage: string;
export const chest: string;
export const classItem: string;
export const energy: string;
export const footNote: string;
export const gauntlets: string;
export const gearGrid: string;
export const gearItem: string;
export const gearItemInfo: string;
export const gearPowerHeader: string;
export const gearPowerSheet: string;
export const gearPowerSheetContent: string;
export const helmet: string;
export const itemImage: string;
export const kinetic: string;
export const leg: string;
export const negative: string;
export const neutral: string;
export const positive: string;
export const power: string;
export const powerLevel: string;
export const powerToggleButton: string;
export const sheetContents: string;
export const statMeta: string;
export const toggle: string;
