// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucketImage': string;
  'chest': string;
  'classItem': string;
  'energy': string;
  'footNote': string;
  'gauntlets': string;
  'gearGrid': string;
  'gearItem': string;
  'gearItemInfo': string;
  'gearPowerHeader': string;
  'gearPowerSheet': string;
  'gearPowerSheetContent': string;
  'helmet': string;
  'itemImage': string;
  'kinetic': string;
  'leg': string;
  'negative': string;
  'neutral': string;
  'notes': string;
  'positive': string;
  'power': string;
  'powerLevel': string;
  'statMeta': string;
}
export const cssExports: CssExports;
export default cssExports;
