// This file is automatically generated.
// Please do not change this file!
export const equipped: string;
export const equippedAddButton: string;
export const itemGrid: string;
export const items: string;
export const loadoutBucket: string;
export const loadoutBucketName: string;
