// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'equipped': string;
  'equippedAddButton': string;
  'itemGrid': string;
  'items': string;
  'loadoutBucket': string;
  'loadoutBucketName': string;
}
export const cssExports: CssExports;
export default cssExports;
