// This file is automatically generated.
// Please do not change this file!
export const dimInput: string;
export const inputGroup: string;
export const loadoutName: string;
export const loadoutOptions: string;
