// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cost': string;
  'currency': string;
  'notEnough': string;
}
export const cssExports: CssExports;
export default cssExports;
