// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const item: string;
export const items: string;
export const missingItem: string;
export const noOrnament: string;
export const right: string;
export const sheet: string;
export const verticalButtons: string;
