// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'items': string;
  'placeholder': string;
  'sheet': string;
  'socket': string;
}
export const cssExports: CssExports;
export default cssExports;
