// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'item': string;
  'items': string;
  'missingItem': string;
  'noSocket': string;
  'right': string;
  'sheet': string;
  'verticalButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
