import { library } from '@fortawesome/fontawesome-svg-core';
import { faTwitter } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowAltCircleUp,
  faCheckCircle as faCheckCircleRegular,
  faCircle as faCircleRegular,
  faMinusSquare,
  faPlusSquare,
  faQuestionCircle,
  faTrashAlt
} from '@fortawesome/free-regular-svg-icons';
import {
  faArrowCircleUp,
  faBars,
  faCheckCircle,
  faCog,
  faDownload,
  faEnvelope,
  faEraser,
  faPlusCircle,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faStar,
  faSync,
  faTable,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faUpload,
  faLevelUpAlt,
  faBan,
  faUndo,
  faPencilAlt,
  faChevronCircleDown,
  faChevronDown,
  faChevronUp,
  faBolt,
  faTag,
  faUser,
  faLeaf
} from '@fortawesome/free-solid-svg-icons';

import { dimEngramIcon, dimPowerIcon, dimPowerAltIcon } from './custom';

// TODO: remove when Angular is out and all icons are imported
//       in JS
library.add(
  faTwitter,

  faArrowAltCircleUp,
  faCheckCircleRegular,
  faCircleRegular,
  faMinusSquare,
  faPlusSquare,
  faQuestionCircle,
  faTrashAlt,

  faArrowCircleUp,
  faBan,
  faBars,
  faBolt,
  faCheckCircle,
  faChevronCircleDown,
  faChevronDown,
  faChevronUp,
  faCog,
  faDownload,
  faEnvelope,
  faEraser,
  faLeaf,
  faLevelUpAlt,
  faPencilAlt,
  faPlusCircle,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faStar,
  faSync,
  faTable,
  faTag,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faUndo,
  faUpload,
  faUser,

  dimEngramIcon,
  dimPowerIcon,
  dimPowerAltIcon
);

export {
  dimEngramIcon as engramIcon,
  dimPowerIcon as powerIndicatorIcon,
  dimPowerAltIcon as powerActionIcon,
  faArrowAltCircleUp as raiseReputationIcon,
  faArrowCircleUp as updateIcon,
  faBan as banIcon,
  faBars as menuIcon,
  faBars as reorderIcon,
  faBolt as boltIcon,
  faCheckCircle as enabledIcon,
  faCheckCircle as redeemedIcon,
  faCheckCircleRegular as completedIcon,
  faChevronCircleDown as openDropdownIcon,
  faCircleRegular as uncompletedIcon,
  faCog as settingsIcon,
  faDownload as downloadIcon,
  faEnvelope as sendIcon,
  faEraser as clearIcon,
  faLeaf as leafIcon,
  faLevelUpAlt as levellingIcon,
  faMinusSquare as collapseIcon,
  faPencilAlt as editIcon,
  faPlusSquare as expandIcon,
  faPlusCircle as addIcon,
  faQuestionCircle as helpIcon,
  faSave as saveIcon,
  faSearch as searchIcon,
  faSignInAlt as signInIcon,
  faSignOutAlt as signOutIcon,
  faChevronDown as moveDownIcon,
  faChevronUp as moveUpIcon,
  faStar as starIcon,
  faSync as refreshIcon,
  faTable as spreadsheetIcon,
  faTag as tagIcon,
  faThumbsUp as thumbsUpIcon,
  faTimes as closeIcon,
  faTimesCircle as disabledIcon,
  faTrashAlt as deleteIcon,
  faTwitter as twitterIcon,
  faUndo as undoIcon,
  faUpload as revisionsIcon,
  faUpload as uploadIcon,
  faUser as userIcon
};
