import { faTwitter } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowAltCircleUp,
  faCheckCircle as faCheckCircleRegular,
  faCircle as faCircleRegular,
  faQuestionCircle,
  faStar as faStarOutline,
  faTrashAlt
} from '@fortawesome/free-regular-svg-icons';
import {
  faArrowCircleUp,
  faBars,
  faCheckCircle,
  faCaretDown,
  faCaretRight,
  faCog,
  faDownload,
  faEnvelope,
  faEraser,
  faPlusCircle,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faStar,
  faSync,
  faTable,
  faThumbsUp,
  faThumbsDown,
  faTimes,
  faTimesCircle,
  faUpload,
  faLevelUpAlt,
  faLock,
  faUnlock,
  faBan,
  faUndo,
  faPencilAlt,
  faChevronCircleDown,
  faChevronDown,
  faChevronUp,
  faBolt,
  faTag,
  faCopy,
  faPlus,
  faArrowRight,
  faHeart,
  faStarHalfAlt,
  faGlobe,
  faStickyNote
} from '@fortawesome/free-solid-svg-icons';

import {
  dimEngramIcon,
  dimPowerIcon,
  dimPowerAltIcon,
  dimHunterIcon,
  dimTitanIcon,
  dimWarlockIcon,
  stadiaIcon,
  battleNetIcon
} from './custom';

export {
  battleNetIcon,
  stadiaIcon,
  dimEngramIcon as engramIcon,
  dimPowerIcon as powerIndicatorIcon,
  dimPowerAltIcon as powerActionIcon,
  dimHunterIcon as hunterIcon,
  dimTitanIcon as titanIcon,
  dimWarlockIcon as warlockIcon,
  faArrowAltCircleUp as raiseReputationIcon,
  faArrowCircleUp as updateIcon,
  faArrowRight as rightArrowIcon,
  faBan as banIcon,
  faBars as menuIcon,
  faBars as reorderIcon,
  faBolt as boltIcon,
  faCheckCircle as enabledIcon,
  faCheckCircle as redeemedIcon,
  faCheckCircleRegular as completedIcon,
  faCheckCircleRegular as unselectedCheckIcon,
  faChevronCircleDown as openDropdownIcon,
  faCircleRegular as uncompletedIcon,
  faCog as settingsIcon,
  faCopy as copyIcon,
  faDownload as downloadIcon,
  faEnvelope as sendIcon,
  faEraser as clearIcon,
  faLevelUpAlt as levellingIcon,
  faLock as lockIcon,
  faUnlock as unlockedIcon,
  faCaretDown as collapseIcon,
  faPencilAlt as editIcon,
  faPlus as plusIcon,
  faCaretRight as expandIcon,
  faPlusCircle as addIcon,
  faQuestionCircle as helpIcon,
  faSave as saveIcon,
  faSearch as searchIcon,
  faSignInAlt as signInIcon,
  faSignOutAlt as signOutIcon,
  faChevronDown as moveDownIcon,
  faChevronUp as moveUpIcon,
  faStar as starIcon,
  faStarHalfAlt as halfStarIcon,
  faStarOutline as starOutlineIcon,
  faSync as refreshIcon,
  faTable as spreadsheetIcon,
  faTag as tagIcon,
  faThumbsUp as thumbsUpIcon,
  faThumbsDown as thumbsDownIcon,
  faTimes as closeIcon,
  faTimesCircle as disabledIcon,
  faTrashAlt as deleteIcon,
  faTwitter as twitterIcon,
  faUndo as undoIcon,
  faUpload as revisionsIcon,
  faUpload as uploadIcon,
  faHeart as heartIcon,
  faGlobe as globeIcon,
  faStickyNote as stickyNoteIcon
};
