// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorizationChallenge': string;
  'confirmButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
