// This file is automatically generated.
// Please do not change this file!
export const connected: string;
export const error: string;
export const streamDeckButton: string;
export const tooltipTitle: string;
export const versionTable: string;
