// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'connected': string;
  'error': string;
  'streamDeckButton': string;
  'tooltipTitle': string;
  'versionTable': string;
}
export const cssExports: CssExports;
export default cssExports;
