// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'emptySlot': string;
  'header': string;
  'slotNum': string;
  'slots': string;
}
export const cssExports: CssExports;
export = cssExports;
