// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'checked': string;
  'content': string;
  'header': string;
  'imageButton': string;
  'preview': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
