// This file is automatically generated.
// Please do not change this file!
export const content: string;
export const emptySlot: string;
export const header: string;
export const slotNum: string;
export const slots: string;
