// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconImg': string;
  'index': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export = cssExports;
