// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'categoryArmor': string;
  'categoryWeapons': string;
  'contents': string;
  'icon': string;
  'itemCategory': string;
  'itemsInCategory': string;
  'loadout': string;
  'loadoutSlot': string;
  'modsGrid': string;
  'placeholder': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
