// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'header': string;
  'itemGroups': string;
  'itemImage': string;
  'loadoutGrid': string;
  'sheet': string;
  'smallSockets': string;
}
export const cssExports: CssExports;
export = cssExports;
