// This file is automatically generated.
// Please do not change this file!
export const deleteDanger: string;
export const equipAlready: string;
export const equipNok: string;
export const equipOk: string;
export const igtIcon: string;
export const igtIconHolder: string;
export const inGameTile: string;
export const inGameTileWrapper: string;
export const isEquipped: string;
export const kebab: string;
export const loadoutStrip: string;
export const matchingLoadouts: string;
export const statusAppIcon: string;
