// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blankBox': string;
  'deleteDanger': string;
  'equipNok': string;
  'equipOk': string;
  'igtIcon': string;
  'igtIconHolder': string;
  'inGameTile': string;
  'inGameTileWrapper': string;
  'isEquipped': string;
  'kebab': string;
  'loadoutStrip': string;
  'matchingLoadouts': string;
  'statusAppIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
