// This file is automatically generated.
// Please do not change this file!
export const controls: string;
export const header: string;
export const itemGroups: string;
export const itemImage: string;
export const loadoutGrid: string;
export const sheet: string;
export const smallSockets: string;
