// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'checked': string;
  'hasLoadout': string;
  'spaced': string;
}
export const cssExports: CssExports;
export default cssExports;
