version: 2
updates:
  - directory: /
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      time: "18:00" # UTC, = ~10AM Pacific
    groups:
      major:
        update-types:
          - major
      minor:
        update-types:
          - minor
          - patch

  - directory: /
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      time: "18:00" # UTC, = ~10AM Pacific
    groups:
      major:
        update-types:
          - major
      minor:
        update-types:
          - minor
          - patch

  # Dependabot doesn't support docker-compose yet
  # - directory: /
  #   package-ecosystem: "docker"
  #   schedule:
  #     interval: "weekly"
  #     time: "18:00" # UTC, = ~10AM Pacific
