// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'hotkeys': string;
  'key': string;
  'keys': string;
  'list': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
