// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const hotkeys: string;
export const key: string;
export const keys: string;
export const list: string;
export const text: string;
export const title: string;
