// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artifactProgress': string;
  'xpIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
