// This file is automatically generated.
// Please do not change this file!
export const badge: string;
export const badgeContent: string;
export const capped: string;
export const deepsight: string;
export const engram: string;
export const fixContrast: string;
export const fullstack: string;
export const masterwork: string;
export const quality: string;
