// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'badge': string;
  'capped': string;
  'energyCapacity': string;
  'energyCapacityIcon': string;
  'engram': string;
  'fixContrast': string;
  'fullstack': string;
  'masterwork': string;
  'quality': string;
  'solar': string;
  'stasis': string;
  'void': string;
  'wishlistRoll': string;
}
export const cssExports: CssExports;
export default cssExports;
