// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dragPerfFix': string;
  'dragPerfShow': string;
}
export const cssExports: CssExports;
export = cssExports;
