// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cantDrag': string;
  'engram': string;
  'inPostmasterCantTransfer': string;
}
export const cssExports: CssExports;
export default cssExports;
