// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'element': string;
  'void': string;
}
declare const cssExports: CssExports;
export = cssExports;
