// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'element': string;
  'void': string;
}
export const cssExports: CssExports;
export default cssExports;
