// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'element': string;
  'lightBackground': string;
}
export const cssExports: CssExports;
export default cssExports;
