// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cover': string;
  'searchOpen': string;
  'shadow': string;
}
export const cssExports: CssExports;
export default cssExports;
