// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasBadge': string;
  'icon': string;
  'icons': string;
  'searchHidden': string;
  'subclass': string;
  'subclassBase': string;
  'subclassSuperIcon': string;
  'warningIcon': string;
  'xpBar': string;
  'xpBarAmount': string;
}
export const cssExports: CssExports;
export default cssExports;
