// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'basic': string;
  'borderless': string;
  'common': string;
  'complete': string;
  'exotic': string;
  'exoticMasterwork': string;
  'icon': string;
  'iconOverlay': string;
  'icons': string;
  'legendary': string;
  'masterwork': string;
  'masterworkOverlay': string;
  'rare': string;
  'searchHidden': string;
  'subclass': string;
  'subclassPathBottom': string;
  'subclassPathMiddle': string;
  'subclassPathTop': string;
  'touchActive': string;
  'xpBar': string;
  'xpBarAmount': string;
}
export const cssExports: CssExports;
export default cssExports;
