// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundOverlay': string;
  'basic': string;
  'borderless': string;
  'common': string;
  'complete': string;
  'deepsight': string;
  'deepsightBorder': string;
  'energyCost': string;
  'energyCostOverlay': string;
  'exotic': string;
  'exoticMasterwork': string;
  'highlightedObjective': string;
  'iconOverlay': string;
  'inverted': string;
  'legendary': string;
  'legendaryMasterwork': string;
  'masterwork': string;
  'rare': string;
  'shinyMasterwork': string;
  'strandColorFix': string;
  'tierPip': string;
  'tierPipContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
