// This file is automatically generated.
// Please do not change this file!
export const bucketName: string;
export const itemPowerSet: string;
export const negative: string;
export const positive: string;
export const powerDiff: string;
export const spanGrid: string;
