// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'note': string;
  'noteIcon': string;
  'notes': string;
  'perkSelected': string;
  'perks': string;
  'stats': string;
}
export const cssExports: CssExports;
export default cssExports;
