// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucketName': string;
  'dimmed': string;
  'invert': string;
  'itemPowerSet': string;
  'powerDiff': string;
  'spanGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
