// This file is automatically generated.
// Please do not change this file!
export const adjustOpacity: string;
export const animatedBackground: string;
export const basic: string;
export const borderless: string;
export const common: string;
export const complete: string;
export const craftedLayer: string;
export const deepsight: string;
export const energyCost: string;
export const exotic: string;
export const highlightedObjective: string;
export const inverted: string;
export const legendary: string;
export const masterwork: string;
export const rare: string;
export const seasonIcon: string;
export const shiftedLayer: string;
export const strandColorFix: string;
