// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'failed': string;
  'progressIcon': string;
  'succeeded': string;
}
declare const cssExports: CssExports;
export = cssExports;
