// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorList': string;
  'failed': string;
  'iconList': string;
  'loadoutDetails': string;
  'loadoutItemFailed': string;
  'loadoutItemPending': string;
  'progressIcon': string;
  'succeeded': string;
  'warning': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
