// This file is automatically generated.
// Please do not change this file!
export const errorList: string;
export const failed: string;
export const iconList: string;
export const loadoutDetails: string;
export const loadoutItemFailed: string;
export const loadoutItemPending: string;
export const progressIcon: string;
export const succeeded: string;
export const warning: string;
export const warningIcon: string;
