// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'button': string;
  'buttonContents': string;
}
export const cssExports: CssExports;
export default cssExports;
