// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'godroll': string;
  'trashlist': string;
}
export const cssExports: CssExports;
export = cssExports;
