// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucket': string;
  'bucketTag': string;
  'currency': string;
  'full': string;
  'vaultStats': string;
}
declare const cssExports: CssExports;
export = cssExports;
