// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucket': string;
  'bucketTag': string;
  'currency': string;
  'full': string;
  'vaultStats': string;
}
export const cssExports: CssExports;
export default cssExports;
