// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorization': string;
  'authorizationButtons': string;
  'authorizationChallenge': string;
}
export const cssExports: CssExports;
export default cssExports;
