engines:
  duplication:
    config:
      languages:
        - javascript
        - php
    enabled: true
  eslint:
    channel: eslint-2
    checks:
      complexity:
        enabled: true
    enabled: true
  fixme:
    enabled: true
exclude_paths:
  - "**/vendor"
  - "**/jquery-ui.position.js"
  - "**/build"
ratings:
  paths:
    - "**.js"
