engines:
  eslint:
    enabled: false
    checks:
      complexity:
        enabled: false
    channel: "eslint-2"
  duplication:
    enabled: true
        config:
          languages:
          - javascript
          - php
  fixme:
    enabled: true

ratings:
   paths:
   - "**.js"

exclude_paths:
  - "**/vendor"
  - "**/jquery-ui.position.js"
  - "**/build"
