"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"files": [
  {
    "source": "src/locale/en.json",
    "translation": "src/locale/%android_code%.json",
    "type": "i18next_json"
  }
]