// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modifier': string;
  'small': string;
}
export const cssExports: CssExports;
export = cssExports;
