// This file is automatically generated.
// Please do not change this file!
export const count: string;
export const guide: string;
export const invert: string;
export const pill: string;
export const pullItem: string;
export const selected: string;
export const synergy: string;
