// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'guide': string;
  'invert': string;
  'pill': string;
  'pullItem': string;
  'selected': string;
  'synergy': string;
}
export const cssExports: CssExports;
export default cssExports;
