// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'info': string;
  'item': string;
  'sideTray': string;
  'title': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
