// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boolean': string;
  'checkbox': string;
  'complete': string;
  'counter': string;
  'description': string;
  'integer': string;
  'objective': string;
  'objectiveComplete': string;
  'passageFlawed': string;
  'progressBar': string;
  'progressContainer': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
