// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'counter': string;
  'dateTime': string;
  'integer': string;
  'passageFlawed': string;
}
export const cssExports: CssExports;
export default cssExports;
