// This file is automatically generated.
// Please do not change this file!
export const booleanValue: string;
export const checkbox: string;
export const complete: string;
export const counter: string;
export const description: string;
export const integer: string;
export const objective: string;
export const objectiveComplete: string;
export const passageFlawed: string;
export const progressBar: string;
export const progressContainer: string;
export const text: string;
