// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pinnaclecap': string;
  'powercap': string;
  'powercapLabel': string;
  'powercapValue': string;
  'powercaps': string;
}
export const cssExports: CssExports;
export default cssExports;
