// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuLinks': string;
  'progress': string;
}
export const cssExports: CssExports;
export = cssExports;
