// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'complete': string;
  'expired': string;
  'flawedPassage': string;
  'fullstack': string;
  'image': string;
  'progress': string;
  'progressAmount': string;
  'pursuit': string;
  'tracked': string;
  'trackedIcon': string;
}
export const cssExports: CssExports;
export = cssExports;
