// This file is automatically generated.
// Please do not change this file!
export const amount: string;
export const complete: string;
export const expired: string;
export const flawedPassage: string;
export const fullstack: string;
export const image: string;
export const progress: string;
export const progressAmount: string;
export const pursuit: string;
export const tracked: string;
export const trackedIcon: string;
