// This file is automatically generated.
// Please do not change this file!
export const activityRank: string;
export const crucibleRankIcon: string;
export const crucibleRankProgress: string;
export const crucibleRankTotalProgress: string;
export const faction: string;
export const factionInfo: string;
export const factionLevel: string;
export const factionName: string;
export const gridLayout: string;
export const max: string;
export const rankIcon: string;
export const winStreak: string;
