// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityRank': string;
  'bonusRank': string;
  'crucibleRankIcon': string;
  'crucibleRankProgress': string;
  'crucibleRankTotalProgress': string;
  'faction': string;
  'factionIcon': string;
  'factionInfo': string;
  'factionLevel': string;
  'factionName': string;
  'rankIcon': string;
  'winStreak': string;
}
export const cssExports: CssExports;
export default cssExports;
