// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityRank': string;
  'free': string;
  'gridLayout': string;
  'hasPremiumRewards': string;
  'premium': string;
  'progress': string;
  'progressBar': string;
  'season': string;
  'seasonEnd': string;
  'seasonInfo': string;
  'seasonLevel': string;
  'seasonName': string;
  'seasonRankIcon': string;
  'seasonRankProgress': string;
  'seasonalRewardWrapper': string;
  'seasonalRewards': string;
  'seassonTitle': string;
}
export const cssExports: CssExports;
export = cssExports;
