// This file is automatically generated.
// Please do not change this file!
export const activityRank: string;
export const free: string;
export const gridLayout: string;
export const hasPremiumRewards: string;
export const premium: string;
export const progress: string;
export const progressBar: string;
export const season: string;
export const seasonalRewards: string;
export const seasonalRewardWrapper: string;
export const seasonEnd: string;
export const seasonInfo: string;
export const seasonLevel: string;
export const seasonName: string;
export const seasonRankIcon: string;
export const seasonRankProgress: string;
export const seassonTitle: string;
