// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'free': string;
  'hasPremiumRewards': string;
  'premium': string;
  'progress': string;
  'progressBar': string;
  'seasonEnd': string;
  'seasonalRewardWrapper': string;
  'seasonalRewards': string;
}
export const cssExports: CssExports;
export default cssExports;
