// This file is automatically generated.
// Please do not change this file!
export const icon: string;
export const infuseActions: string;
export const infuseDialog: string;
export const infuseHeader: string;
export const infuseSearch: string;
export const infuseSelected: string;
export const infuseSources: string;
export const infuseTopRow: string;
export const infusionControls: string;
export const infusionEquation: string;
export const missingItem: string;
