// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'infuseActions': string;
  'infuseDialog': string;
  'infuseHeader': string;
  'infuseSearch': string;
  'infuseSelected': string;
  'infuseSources': string;
  'infuseTopRow': string;
  'infusionControls': string;
  'infusionEquation': string;
  'missingItem': string;
}
export const cssExports: CssExports;
export default cssExports;
