// This file is automatically generated.
// Please do not change this file!
export const clickable: string;
export const empty: string;
export const hasBadge: string;
export const placeholder: string;
