// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'empty': string;
  'placeholder': string;
}
export const cssExports: CssExports;
export default cssExports;
