// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fashion': string;
  'items': string;
  'missingItem': string;
  'unequipped': string;
}
export const cssExports: CssExports;
export default cssExports;
