// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artifactUnlock': string;
  'buttons': string;
  'fineprint': string;
  'missingItem': string;
  'modsGrid': string;
  'modsPlaceholder': string;
  'pickModButton': string;
}
export const cssExports: CssExports;
export = cssExports;
