// This file is automatically generated.
// Please do not change this file!
export const missingItem: string;
export const modsPlaceholder: string;
export const power: string;
export const subclass: string;
export const subclassContainer: string;
export const subclassMods: string;
