// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'missingItem': string;
  'mods': string;
  'modsGrid': string;
  'modsPlaceholder': string;
  'showModPlacementButton': string;
}
export const cssExports: CssExports;
export default cssExports;
