// This file is automatically generated.
// Please do not change this file!
export const armorSubInfo: string;
export const categoryArmor: string;
export const categoryGeneral: string;
export const categoryWeapons: string;
export const equipped: string;
export const hasSetBonus: string;
export const itemBucket: string;
export const itemCategory: string;
export const items: string;
export const itemsInCategory: string;
export const missingItem: string;
export const placeholder: string;
export const setBonusWrapper: string;
export const unequipped: string;
