// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'constraintRange': string;
  'loExotic': string;
  'loParams': string;
  'loQuery': string;
  'loStat': string;
  'loStats': string;
}
export const cssExports: CssExports;
export default cssExports;
