// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armorSubInfo': string;
  'categoryArmor': string;
  'categoryGeneral': string;
  'categoryWeapons': string;
  'equipped': string;
  'hasSetBonus': string;
  'itemBucket': string;
  'itemCategory': string;
  'items': string;
  'itemsInCategory': string;
  'missingItem': string;
  'placeholder': string;
  'setBonusWrapper': string;
  'unequipped': string;
}
export const cssExports: CssExports;
export = cssExports;
