// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'automaticallyPicked': string;
  'lockedItems': string;
  'small': string;
  'vendorItem': string;
}
export const cssExports: CssExports;
export default cssExports;
