// This file is automatically generated.
// Please do not change this file!
export const automaticallyPicked: string;
export const lockedItems: string;
export const small: string;
export const vendorItem: string;
