// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const content: string;
export const inventoryContainer: string;
export const singleCharacter: string;
export const singleCharacterButton: string;
