// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'content': string;
  'inventoryContainer': string;
  'singleCharacter': string;
  'singleCharacterButton': string;
}
export const cssExports: CssExports;
export default cssExports;
