// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucketSize': string;
  'clickToExpand': string;
  'collapsed': string;
  'postmasterFull': string;
  'spanColumns': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
