// This file is automatically generated.
// Please do not change this file!
export const bucketSize: string;
export const clickToExpand: string;
export const collapsed: string;
export const postmasterFull: string;
export const spanColumns: string;
export const title: string;
