// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'character': string;
  'frame': string;
  'track': string;
}
export const cssExports: CssExports;
export = cssExports;
