// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucketSize': string;
  'collapsed': string;
  'content': string;
  'handle': string;
  'postmasterFull': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
