// This file is automatically generated.
// Please do not change this file!
export const armorClassIcon: string;
export const emptyEngram: string;
export const engrams: string;
export const inlineGroups: string;
export const notEquippable: string;
export const pullItemButton: string;
export const subClass: string;
export const vaultGroup: string;
export const weaponGroupingIconWrapper: string;
