// This file is automatically generated.
// Please do not change this file!
export const accountWideCell: string;
export const bucketLabel: string;
export const hasButton: string;
export const postmasterFull: string;
export const singleCharacterAccountWideRow: string;
