// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canDrop': string;
  'equipped': string;
  'grouped': string;
  'over': string;
  'unequipped': string;
}
export const cssExports: CssExports;
export = cssExports;
