// This file is automatically generated.
// Please do not change this file!
export const canDrop: string;
export const equipped: string;
export const grouped: string;
export const over: string;
export const unequipped: string;
