// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountWideCell': string;
  'bucketLabel': string;
  'hasButton': string;
  'postmasterFull': string;
  'singleCharacterAccountWideRow': string;
  'vaultCell': string;
  'vaultUnder': string;
}
export const cssExports: CssExports;
export = cssExports;
