// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badPerk': string;
  'goodPerk': string;
  'lockedPerk': string;
  'perk': string;
  'perkDescription': string;
  'perkInfo': string;
  'perkTitle': string;
  'unselectable': string;
}
declare var cssExports: CssExports;
export = cssExports;
