// This file is automatically generated.
// Please do not change this file!
export const levelBar: string;
export const levelBarProgress: string;
export const moteProgress: string;
export const xpBar: string;
