// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'bottom': string;
  'characterText': string;
  'characterTile': string;
  'class': string;
  'classIcon': string;
  'emblem': string;
  'gildedCurrentSeason': string;
  'gildedIcon': string;
  'gildedNum': string;
  'level': string;
  'maxTotalPower': string;
  'powerLevel': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
