// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bigPowerLevel': string;
  'bigText': string;
  'bottom': string;
  'characterTile': string;
  'class': string;
  'current': string;
  'emblem': string;
  'gildedCurrentSeason': string;
  'gildedIcon': string;
  'gildedNum': string;
  'maxTotalPower': string;
  'powerLevel': string;
  'smallPowerLevel': string;
  'smallText': string;
  'tileCommon': string;
  'title': string;
  'vaultCapacity': string;
  'vaultEmblem': string;
  'vaultName': string;
  'vaultTile': string;
}
export const cssExports: CssExports;
export default cssExports;
