// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'levelBar': string;
  'levelBarProgress': string;
  'moteProgress': string;
  'xpBar': string;
}
export const cssExports: CssExports;
export = cssExports;
