// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadoutButton': string;
  'loadoutMenu': string;
}
export const cssExports: CssExports;
export default cssExports;
