// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'dimmedBg': string;
  'label': string;
}
export const cssExports: CssExports;
export = cssExports;
