// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'energySelect': string;
  'title': string;
  'unused': string;
  'used': string;
}
export const cssExports: CssExports;
export default cssExports;
