// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'energyOptions': string;
  'settingGroup': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
