// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'energyOptions': string;
  'option': string;
}
export const cssExports: CssExports;
export default cssExports;
