// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'details': string;
  'exotic': string;
  'header': string;
  'info': string;
  'itemImage': string;
  'itemName': string;
  'items': string;
  'perkDescription': string;
  'perkImage': string;
  'perkName': string;
  'perkNameAndImage': string;
}
export const cssExports: CssExports;
export default cssExports;
