// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'perkOrModImage': string;
  'perkOrModNameAndImage': string;
}
export const cssExports: CssExports;
export = cssExports;
