// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'exotic': string;
  'header': string;
  'itemImage': string;
  'items': string;
  'perk': string;
}
export const cssExports: CssExports;
export default cssExports;
