// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemName': string;
  'perkDescription': string;
  'perkOrModImage': string;
  'perkOrModNameAndImage': string;
}
export const cssExports: CssExports;
export default cssExports;
