// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chosenSetBonus': string;
  'container': string;
  'footer': string;
  'perkIcon': string;
  'selectedBonuses': string;
  'setCount': string;
  'submitButton': string;
}
export const cssExports: CssExports;
export default cssExports;
