// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const footer: string;
export const selectedBonuses: string;
export const setBonuses: string;
export const setCount: string;
export const submitButton: string;
