// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'details': string;
  'infoCard': string;
  'selectedPerk': string;
  'selectedPerks': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
