// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'infoCard': string;
  'title': string;
  'warning': string;
}
export const cssExports: CssExports;
export = cssExports;
