// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'footer': string;
  'selectedBonuses': string;
  'setBonuses': string;
  'setCount': string;
  'submitButton': string;
}
export const cssExports: CssExports;
export = cssExports;
