// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'area': string;
  'buttons': string;
  'guide': string;
  'itemGrid': string;
  'notItemGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
