// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'grip': string;
  'iconStat': string;
  'ignored': string;
  'maxed': string;
  'row': string;
  'rowControl': string;
  'selectedStatBar': string;
  'statBar': string;
  'statBarSegment': string;
  'statDisplayInfo': string;
  'statName': string;
}
export const cssExports: CssExports;
export default cssExports;
