// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'dragging': string;
  'editor': string;
  'grip': string;
  'iconStat': string;
  'ignored': string;
  'label': string;
  'maxRestricted': string;
  'maxed': string;
  'name': string;
  'row': string;
  'rowControl': string;
  'selectedStatBar': string;
  'statBar': string;
  'statBarSegment': string;
}
export const cssExports: CssExports;
export default cssExports;
