// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const editor: string;
export const grabHandle: string;
export const grip: string;
export const iconStat: string;
export const ignored: string;
export const label: string;
export const name: string;
export const processing: string;
export const processingPulse: string;
export const row: string;
export const rowControl: string;
export const statBar: string;
export const statBarFill: string;
export const statBarMax: string;
export const statBarMin: string;
export const statRange: string;
