// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grip': string;
  'iconStat': string;
  'ignored': string;
  'maximum': string;
  'minimum': string;
  'range': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
