// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'dragging': string;
  'editor': string;
  'grip': string;
  'iconStat': string;
  'ignored': string;
  'label': string;
  'name': string;
  'processing': string;
  'processingPulse': string;
  'row': string;
  'rowControl': string;
  'statBar': string;
  'statBarFill': string;
  'statBarMax': string;
  'statBarMin': string;
  'statRange': string;
}
export const cssExports: CssExports;
export default cssExports;
