// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inlineImageIcon': string;
  'intrinsicIcon': string;
  'svgIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
