// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'forCompare': string;
  'masterwork': string;
  'range': string;
  'stat': string;
  'statValue': string;
}
export const cssExports: CssExports;
export default cssExports;
