// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'compareItem': string;
  'header': string;
  'initialItem': string;
  'isFindable': string;
  'itemAside': string;
  'itemName': string;
}
export const cssExports: CssExports;
export default cssExports;
