// This file is automatically generated.
// Please do not change this file!
export const customStat: string;
export const masterwork: string;
export const noMinWidth: string;
export const range: string;
export const smaller: string;
export const stat: string;
export const statBarArea: string;
export const statBarContainer: string;
export const statBarFill: string;
export const statExceptionIndicator: string;
export const statValue: string;
