// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'header': string;
  'headerContainer': string;
  'highlightBar': string;
  'itemActions': string;
  'itemAside': string;
  'lastRow': string;
  'separator': string;
  'sortAsc': string;
  'sortDesc': string;
  'spacer': string;
  'statList': string;
}
export const cssExports: CssExports;
export default cssExports;
