// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'archetype': string;
  'energy': string;
  'miniPerkContainer': string;
  'modPerk': string;
  'name': string;
  'nameHeader': string;
  'noWrap': string;
  'perks': string;
  'stats': string;
  'talentGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
