// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'name': string;
  'nameHeader': string;
  'stats': string;
}
export const cssExports: CssExports;
export default cssExports;
