// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bucket': string;
  'options': string;
  'organizerLink': string;
  'scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
