// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'compareItem': string;
  'header': string;
  'highlightBar': string;
  'initialItem': string;
  'isFindable': string;
  'itemAside': string;
  'itemName': string;
  'sortAsc': string;
  'sortDesc': string;
  'spacer': string;
  'statLabel': string;
  'statList': string;
  'talentGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
