// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'range': string;
  'recoil': string;
  'stat': string;
}
export const cssExports: CssExports;
export default cssExports;
