// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorized': string;
  'icon': string;
  'mask': string;
}
export const cssExports: CssExports;
export default cssExports;
