// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'full': string;
  'gauge': string;
  'warningBlock': string;
}
export const cssExports: CssExports;
export = cssExports;
