// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'itemActions': string;
}
export const cssExports: CssExports;
export default cssExports;
