// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centered': string;
  'dmg': string;
  'dmgHeader': string;
  'enhancedArrow': string;
  'hasFilter': string;
  'header': string;
  'icon': string;
  'iconHeader': string;
  'importButton': string;
  'inlineIcon': string;
  'isPerk': string;
  'loadout': string;
  'locationCell': string;
  'miniPerkContainer': string;
  'modPerk': string;
  'modPerks': string;
  'modslotIcon': string;
  'name': string;
  'negative': string;
  'new': string;
  'noItems': string;
  'noWrap': string;
  'perkLike': string;
  'perkSelectable': string;
  'perkSelected': string;
  'perks': string;
  'positive': string;
  'recoil': string;
  'selection': string;
  'shapedIconOverlay': string;
  'shiftHeld': string;
  'sorter': string;
  'stats': string;
  'table': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
