// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'checkButton': string;
  'dropDown': string;
  'menu': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
