// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enabledColumns': string;
  'enabledColumnsButton': string;
  'enabledColumnsCheckButton': string;
  'enabledColumnsDropDown': string;
}
export const cssExports: CssExports;
export default cssExports;
