// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonItemCount': string;
  'level': string;
  'selector': string;
}
export const cssExports: CssExports;
export = cssExports;
