// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'checked': string;
  'level': string;
  'selector': string;
}
export const cssExports: CssExports;
export default cssExports;
