// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasFilter': string;
  'header': string;
  'headerRow': string;
  'importButton': string;
  'noItems': string;
  'row': string;
  'selection': string;
  'shiftHeld': string;
  'sorter': string;
  'table': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export = cssExports;
