// This file is automatically generated.
// Please do not change this file!
export const actionButton: string;
export const itemActions: string;
export const keyHelp: string;
export const label: string;
export const storeName: string;
export const tip: string;
