// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'archetype': string;
  'base2715839340': string;
  'customstat': string;
  'dmg': string;
  'energy': string;
  'hasFilter': string;
  'header': string;
  'icon': string;
  'importButton': string;
  'inlineIcon': string;
  'isPerk': string;
  'itemIcon': string;
  'killTrackerDisplay': string;
  'loadouts': string;
  'locationCell': string;
  'locked': string;
  'miniPerkContainer': string;
  'modPerk': string;
  'modPerks': string;
  'modslot': string;
  'modslotIcon': string;
  'name': string;
  'negative': string;
  'new': string;
  'noItems': string;
  'perkSelectable': string;
  'perkSelected': string;
  'perks': string;
  'positive': string;
  'power': string;
  'rating': string;
  'season': string;
  'selection': string;
  'shiftHeld': string;
  'sorter': string;
  'stat2715839340': string;
  'statValue': string;
  'table': string;
  'tag': string;
  'toolbar': string;
  'traits': string;
  'wishList': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
