// This file is automatically generated.
// Please do not change this file!
export const assigned: string;
export const container: string;
export const cost: string;
export const costs: string;
export const energyMeter: string;
export const headerInfo: string;
export const headerName: string;
export const headerStats: string;
export const infoSectionHeader: string;
export const itemAndMods: string;
export const unassigned: string;
