// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'assigned': string;
  'container': string;
  'cost': string;
  'costs': string;
  'energyMeter': string;
  'headerInfo': string;
  'headerName': string;
  'headerStats': string;
  'infoSectionHeader': string;
  'itemAndMods': string;
  'unassigned': string;
}
export const cssExports: CssExports;
export default cssExports;
