// This file is automatically generated.
// Please do not change this file!
export const and: string;
export const controls: string;
export const example: string;
export const excludedItems: string;
export const itemRow: string;
export const lockedButton: string;
export const or: string;
export const perk: string;
export const perkSelectBox: string;
export const perkSelectPopup: string;
export const section: string;
export const shiftHeld: string;
