// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'and': string;
  'controls': string;
  'example': string;
  'excludedItems': string;
  'itemRow': string;
  'lockedButton': string;
  'or': string;
  'perk': string;
  'perkSelectBox': string;
  'perkSelectPopup': string;
  'section': string;
  'shiftHeld': string;
}
export const cssExports: CssExports;
export = cssExports;
