// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'dimStats': string;
  'expandConfigs': string;
  'label': string;
  'loadout': string;
  'set': string;
  'setItem': string;
  'talentGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
