// This file is automatically generated.
// Please do not change this file!
export const controls: string;
export const dimStats: string;
export const expandConfigs: string;
export const label: string;
export const loadout: string;
export const set: string;
export const setItem: string;
export const talentGrid: string;
