// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'onDragEnter': string;
  'onDragHover': string;
}
export const cssExports: CssExports;
export default cssExports;
