// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyItem': string;
  'itemSized': string;
  'label': string;
  'lockedItem': string;
  'perkAddition': string;
  'perkAdditionText': string;
  'perkAdditionTextContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
