// This file is automatically generated.
// Please do not change this file!
export const emptyItem: string;
export const itemSized: string;
export const lockedItem: string;
export const lockPerkIcon: string;
