// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'overlayContainer': string;
  'vendorIconBackground': string;
}
export const cssExports: CssExports;
export default cssExports;
