// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyItem': string;
  'itemSized': string;
  'lockPerkIcon': string;
  'lockedItem': string;
}
export const cssExports: CssExports;
export = cssExports;
