// This file is automatically generated.
// Please do not change this file!
export const and: string;
export const or: string;
export const perk: string;
export const perkSelectBox: string;
export const perkSelectPopup: string;
export const shiftHeld: string;
