// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'and': string;
  'or': string;
  'perk': string;
  'perkSelectBox': string;
  'perkSelectPopup': string;
  'shiftHeld': string;
}
export const cssExports: CssExports;
export default cssExports;
