// Generated by quicktype.io from https://database-clarity.github.io/Character-Stats/schema.json

export interface ClarityCharacterStats {
  CharacterStats: CharacterStats;
  Generic: Generic;
  Ability: Ability;
  Override: Override;
  Mobility: Mobility;
  Recovery: Recovery;
  Resilience: Resilience;
}

export interface Ability {
  type: string;
  additionalProperties: boolean;
  properties: AbilityProperties;
  required: string[];
  title: string;
}

export interface AbilityProperties {
  Hash: Hash;
  Name: Hash;
  Override: Hash;
  Cooldowns: Cooldowns;
}

export interface Cooldowns {
  type: Type;
  items?: Items;
  minItems: number;
  maxItems?: number;
  description?: string;
}

export interface Items {
  type: string;
}

export enum Type {
  Array = 'array',
  Number = 'number',
}

export interface Hash {
  type: string;
  description: string;
}

export interface CharacterStats {
  type: string;
  additionalProperties: boolean;
  properties: CharacterStatsProperties;
  required: string[];
  title: string;
}

export interface CharacterStatsProperties {
  Mobility: Discipline;
  Resilience: Discipline;
  Recovery: Discipline;
  Discipline: Discipline;
  Intellect: Discipline;
  Strength: Discipline;
}

export interface Discipline {
  $ref: string;
}

export interface Generic {
  type: string;
  additionalProperties: boolean;
  properties: GenericProperties;
  required: string[];
  title: string;
}

export interface GenericProperties {
  Abilities: Abilities;
  Overrides: Abilities;
}

export interface Abilities {
  type: Type;
  items: Discipline;
}

export interface Mobility {
  type: string;
  additionalProperties: boolean;
  properties: MobilityProperties;
  required: string[];
  title: string;
}

export interface MobilityProperties {
  WalkingSpeed: Speed;
  StrafeSpeed: Speed;
  CrouchSpeed: Speed;
  Abilities: Abilities;
  Scalars: Abilities;
}

export interface Speed {
  type: Type;
  items: Cooldowns;
}

export interface Override {
  type: string;
  additionalProperties: boolean;
  properties: OverrideProperties;
  required: string[];
  title: string;
}

export interface OverrideProperties {
  Hash: Hash;
  Name: Hash;
  Requirements: Cooldowns;
  CooldownOverride: Cooldowns;
  Scalar: Cooldowns;
  FlatIncrease: Cooldowns;
}

export interface Recovery {
  type: string;
  additionalProperties: boolean;
  properties: RecoveryProperties;
  required: string[];
  title: string;
}

export interface RecoveryProperties {
  TimeToFullHP: TimeToFullHP;
  Abilities: Abilities;
  Scalars: Abilities;
}

export interface TimeToFullHP {
  type: Type;
  items: Cooldowns;
  description: string;
}

export interface Resilience {
  type: string;
  additionalProperties: boolean;
  properties: ResilienceProperties;
  required: string[];
  title: string;
}

export interface ResilienceProperties {
  TotalHP: Cooldowns;
  DamageResistance: Cooldowns;
  FlinchResistance: Cooldowns;
  Abilities: Abilities;
  Scalars: Abilities;
}
