// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'blue': string;
  'bold': string;
  'breakSpaces': string;
  'center': string;
  'communityDescription': string;
  'descriptionDivider': string;
  'enhancedArrow': string;
  'green': string;
  'link': string;
  'purple': string;
  'pve': string;
  'pvp': string;
  'spacer': string;
  'title': string;
  'yellow': string;
}
export const cssExports: CssExports;
export = cssExports;
