// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'background': string;
  'barrier': string;
  'blue': string;
  'bold': string;
  'breakSpaces': string;
  'center': string;
  'communityDescription': string;
  'descriptionDivider': string;
  'enhancedArrow': string;
  'green': string;
  'heavy': string;
  'hunter': string;
  'link': string;
  'overload': string;
  'primary': string;
  'purple': string;
  'pve': string;
  'pvp': string;
  'solar': string;
  'spacer': string;
  'special': string;
  'stasis': string;
  'strand': string;
  'titan': string;
  'title': string;
  'unstoppable': string;
  'void': string;
  'warlock': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
