// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'bold': string;
  'center': string;
  'link': string;
  'spacer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
