// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkboxRow': string;
  'hint': string;
}
export const cssExports: CssExports;
export = cssExports;
