// This file is automatically generated.
// Please do not change this file!
export const altButton: string;
export const content: string;
export const fashionIcon: string;
export const filterInput: string;
export const filterPills: string;
export const inGameLoadoutButton: string;
export const inGameLoadouts: string;
export const list: string;
export const loadoutTypeIcon: string;
export const menuItem: string;
export const modificationIcon: string;
export const moreLoadouts: string;
export const note: string;
export const warningIcon: string;
