// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altButton': string;
  'content': string;
  'filterInput': string;
  'filterPills': string;
  'inGameLoadoutIcon': string;
  'list': string;
  'loadoutTypeIcon': string;
  'menuItem': string;
  'note': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
