// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altButton': string;
  'content': string;
  'filterInput': string;
  'filterPills': string;
  'inGameLoadoutButton': string;
  'inGameLoadouts': string;
  'list': string;
  'loadoutIcon': string;
  'loadoutTypeIcon': string;
  'menuItem': string;
  'moreLoadouts': string;
  'note': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
