// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountName': string;
  'accountSelect': string;
  'logout': string;
}
export const cssExports: CssExports;
export default cssExports;
