// This file is automatically generated.
// Please do not change this file!
export const account: string;
export const accountDetails: string;
export const accountList: string;
export const accountSelect: string;
