// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'connected': string;
  'downloadPlugin': string;
  'notConnected': string;
  'resetButton': string;
}
export const cssExports: CssExports;
export default cssExports;
