// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'container': string;
}
declare const cssExports: CssExports;
export = cssExports;
