// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menuContent': string;
  'page': string;
}
declare const cssExports: CssExports;
export = cssExports;
