// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'area': string;
  'buttons': string;
  'itemGrid': string;
}
declare var cssExports: CssExports;
export = cssExports;
