// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'selectedPerk': string;
  'selectedPerks': string;
  'submitButton': string;
  'tab': string;
  'tabs': string;
}
declare var cssExports: CssExports;
export = cssExports;
