// This file is automatically generated.
// Please do not change this file!
export const auth: string;
export const billboard: string;
export const dimSync: string;
export const dimSyncCheckbox: string;
export const explanation: string;
export const fineprint: string;
export const section: string;
export const warning: string;
