// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth': string;
  'billboard': string;
  'dimSync': string;
  'dimSyncCheckbox': string;
  'explanation': string;
  'fineprint': string;
  'section': string;
  'warning': string;
}
export const cssExports: CssExports;
export = cssExports;
