// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'fillRow': string;
  'header': string;
  'loadoutName': string;
  'noLoadouts': string;
  'setHeader': string;
  'setTitle': string;
}
export const cssExports: CssExports;
export = cssExports;
