// This file is automatically generated.
// Please do not change this file!
export const content: string;
export const fillRow: string;
export const header: string;
export const loadoutName: string;
export const noLoadouts: string;
export const setHeader: string;
export const setTitle: string;
