// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inGameLoadoutList': string;
  'loadoutCount': string;
  'loadoutsBar': string;
}
export const cssExports: CssExports;
export default cssExports;
