// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'assumeMasterwork': string;
  'filters': string;
  'powerSelect': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
