// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'energyHidden': string;
  'energyMeter': string;
  'energySwapContainer': string;
  'energyValue': string;
  'item': string;
  'swapButton': string;
  'swapButtonContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
