// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altPerkKey': string;
  'emptyListReason': string;
  'key': string;
  'newLoadout': string;
  'numSets': string;
  'selectedPerkKey': string;
  'sets': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
