// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'combos': string;
}
declare const cssExports: CssExports;
export = cssExports;
