// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'energyCost': string;
  'energyCostOverlay': string;
  'item': string;
  'perk': string;
}
export const cssExports: CssExports;
export default cssExports;
