// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'build': string;
  'container': string;
  'items': string;
}
export const cssExports: CssExports;
export default cssExports;
