// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyListReason': string;
  'newLoadout': string;
  'numSets': string;
  'sets': string;
}
export const cssExports: CssExports;
export default cssExports;
