// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'energyCost': string;
  'energyCostOverlay': string;
  'item': string;
  'largeEnergyCost': string;
  'largeEnergyCostOverlay': string;
  'largeItem': string;
  'perk': string;
}
export const cssExports: CssExports;
export default cssExports;
