// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'light': string;
  'nonActiveStat': string;
  'statSegment': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
