// This file is automatically generated.
// Please do not change this file!
export const boostedValue: string;
export const container: string;
export const existingLoadout: string;
export const light: string;
export const loadoutName: string;
export const nonActiveStat: string;
export const statIcon: string;
export const statSegment: string;
export const tier: string;
export const tierLightContainer: string;
