// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'existingLoadout': string;
  'halfTierValue': string;
  'light': string;
  'loadoutName': string;
  'nonActiveStat': string;
  'statIcon': string;
  'statSegment': string;
  'statSegmentContainer': string;
  'tier': string;
  'tierLightContainer': string;
  'tierLightSegment': string;
}
export const cssExports: CssExports;
export default cssExports;
