// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grip': string;
  'hiddenOption': string;
  'iconStat': string;
  'ignored': string;
}
export const cssExports: CssExports;
export default cssExports;
