// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grip': string;
  'iconStat': string;
}
declare const cssExports: CssExports;
export = cssExports;
