// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'fineprint': string;
  'icon': string;
  'recipe': string;
  'tertiary': string;
  'verdict': string;
}
export const cssExports: CssExports;
export = cssExports;
