// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alwaysShow': string;
  'newItem': string;
}
export const cssExports: CssExports;
export default cssExports;
