// This file is automatically generated.
// Please do not change this file!
export const body: string;
export const classType: string;
export const header: string;
export const headerDetails: string;
export const inputGroup: string;
export const notes: string;
