// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dimInput': string;
  'inputGroup': string;
  'loadoutName': string;
  'loadoutOptions': string;
}
export const cssExports: CssExports;
export default cssExports;
