// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'classType': string;
  'header': string;
  'headerDetails': string;
  'inputGroup': string;
  'notes': string;
}
export const cssExports: CssExports;
export = cssExports;
