// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'content': string;
  'list': string;
  'loadoutTypeIcon': string;
  'menuItem': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
