// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categories': string;
  'container': string;
  'disclaimer': string;
  'title': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
