// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'selectedPlugs': string;
  'submitButton': string;
}
export const cssExports: CssExports;
export = cssExports;
