// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'elementIcon': string;
  'itemCategoryIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
