// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'stack': string;
  'stackable': string;
}
export const cssExports: CssExports;
export = cssExports;
