// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const clarityDescription: string;
export const stack: string;
export const volumeRocker: string;
