// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'clarityDescription': string;
  'icon': string;
  'stack': string;
}
export const cssExports: CssExports;
export default cssExports;
