// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'requirement': string;
  'stackable': string;
}
export const cssExports: CssExports;
export default cssExports;
