// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badPerk': string;
  'goodPerk': string;
  'lockedPerk': string;
  'perk': string;
  'perkDescription': string;
  'perkInfo': string;
  'perkThumb': string;
  'perkTitle': string;
  'plugStats': string;
  'unselectable': string;
}
export const cssExports: CssExports;
export default cssExports;
