// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'entry': string;
  'label': string;
  'tagSelectorLabelHidden': string;
}
export const cssExports: CssExports;
export = cssExports;
