// This file is automatically generated.
// Please do not change this file!
export const move: string;
export const moveLocationIcons: string;
export const moveLocationPadding: string;
export const moveLocations: string;
export const moveWithVault: string;
export const vaultButton: string;
export const vaultLabel: string;
