// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'move': string;
  'moveLocationIcons': string;
  'moveLocationPadding': string;
  'moveLocations': string;
  'moveWithVault': string;
  'vaultButton': string;
  'vaultLabel': string;
}
export const cssExports: CssExports;
export = cssExports;
