// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'aspects': string;
  'flexColumn': string;
  'flexRow': string;
  'flexWrap': string;
  'fragments': string;
  'optionsGrid': string;
  'resetButton': string;
  'socket': string;
  'sockets': string;
  'super': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
