// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'container': string;
  'selected': string;
  'subclass': string;
  'subclasses': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
