// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'aspects': string;
  'fragments': string;
  'optionsGrid': string;
  'super': string;
  'superImage': string;
}
export const cssExports: CssExports;
export default cssExports;
