// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amazing': string;
  'banner': string;
  'buttongroup': string;
  'confettiToggle': string;
  'container': string;
  'gametwogive': string;
  'goal': string;
  'incentives': string;
  'link': string;
  'maximized': string;
  'mercury': string;
  'streaming': string;
  'thanks': string;
  'thermo': string;
  'toaster': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
