// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'buttongroup': string;
  'container': string;
  'gametwogive': string;
  'goal': string;
  'maximized': string;
  'mercury': string;
  'thermo': string;
  'toaster': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
