// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ammoIcon': string;
  'primary': string;
}
export const cssExports: CssExports;
export = cssExports;
