// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'insertButton': string;
}
export const cssExports: CssExports;
export = cssExports;
