// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakerTypeContainer': string;
  'info': string;
  'isWeapons': string;
  'mod': string;
  'name': string;
  'row': string;
}
export const cssExports: CssExports;
export = cssExports;
