// This file is automatically generated.
// Please do not change this file!
export const info: string;
export const isWeapons: string;
export const mod: string;
export const name: string;
export const row: string;
