// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artifactBreaker': string;
  'breakerIcon': string;
}
export const cssExports: CssExports;
export = cssExports;
