// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'collapseButton': string;
  'collapsed': string;
  'disabled': string;
  'entry': string;
  'equip': string;
  'hideLabel': string;
  'interaction': string;
  'itemTagSelector': string;
  'move': string;
  'moveLocationIcons': string;
  'moveLocations': string;
  'null': string;
}
export const cssExports: CssExports;
export default cssExports;
