// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapseButton': string;
  'collapsed': string;
  'disabled': string;
  'equip': string;
  'hideWhenCollapsed': string;
  'interaction': string;
  'move': string;
  'moveLocationIcons': string;
  'moveLocations': string;
  'vaultLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
