// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'cost': string;
  'elementSelect': string;
  'energyMeter': string;
  'icon': string;
  'upgradeButton': string;
  'upgradePreview': string;
}
export const cssExports: CssExports;
export default cssExports;
