// This file is automatically generated.
// Please do not change this file!
export const cost: string;
export const energyMeter: string;
export const upgradeButton: string;
export const upgradePreview: string;
