// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cost': string;
  'energyMeter': string;
  'upgradeButton': string;
  'upgradePreview': string;
}
export const cssExports: CssExports;
export = cssExports;
