// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemPerk': string;
  'itemPerkName': string;
}
export const cssExports: CssExports;
export default cssExports;
