// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'common': string;
  'desktopActions': string;
  'desktopPopup': string;
  'desktopPopupBody': string;
  'desktopPopupRoot': string;
  'exotic': string;
  'legendary': string;
  'mobileItemActions': string;
  'mobileMoveLocations': string;
  'movePopupDialog': string;
  'popupBackground': string;
  'rare': string;
  'uncommon': string;
}
export const cssExports: CssExports;
export default cssExports;
