// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNote': string;
  'addNoteTag': string;
  'description': string;
  'descriptionTools': string;
  'lore': string;
  'officialDescription': string;
}
declare var cssExports: CssExports;
export = cssExports;
