// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armorIntrinsicDescription': string;
  'clarityDescription': string;
  'clarityDescriptionCommunityOnly': string;
  'generalSockets': string;
  'minimalSockets': string;
}
export const cssExports: CssExports;
export default cssExports;
