// This file is automatically generated.
// Please do not change this file!
export const acquiredIcon: string;
export const fullImage: string;
export const itemDescription: string;
export const itemDetailsBody: string;
export const itemShader: string;
export const itemSource: string;
export const milestoneImage: string;
export const ownedIcon: string;
