// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasIcons': string;
  'stats': string;
}
declare const cssExports: CssExports;
export = cssExports;
