// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armory': string;
  'common': string;
  'details': string;
  'elementIcon': string;
  'exotic': string;
  'header': string;
  'iconOverlay': string;
  'itemType': string;
  'legendary': string;
  'masterwork': string;
  'power': string;
  'pursuit': string;
  'rare': string;
  'subtitle': string;
  'title': string;
  'type': string;
  'uncommon': string;
}
export const cssExports: CssExports;
export default cssExports;
