// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'archetype': string;
  'archetypeMod': string;
  'perks': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
