// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exoticDescription': string;
  'minimalSockets': string;
}
export const cssExports: CssExports;
export default cssExports;
