// This file is automatically generated.
// Please do not change this file!
export const armory: string;
export const common: string;
export const details: string;
export const elementIcon: string;
export const exotic: string;
export const header: string;
export const iconOverlay: string;
export const itemType: string;
export const legendary: string;
export const masterwork: string;
export const power: string;
export const pursuit: string;
export const rare: string;
export const subtitle: string;
export const title: string;
export const type: string;
export const uncommon: string;
