// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'failureReason': string;
  'movePopupTab': string;
  'movePopupTabs': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
