// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acquiredIcon': string;
  'itemDescription': string;
  'itemDetailsBody': string;
  'itemShader': string;
  'itemSource': string;
  'mods': string;
  'ownedIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
