// This file is automatically generated.
// Please do not change this file!
export const item: string;
export const itemTagSelector: string;
export const keyHelp: string;
export const minimized: string;
export const noTag: string;
