// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armor': string;
  'destiny2': string;
  'infusePerk': string;
  'interaction': string;
  'moveConsolidate': string;
  'moveDistribute': string;
  'weapons': string;
}
declare const cssExports: CssExports;
export = cssExports;
