// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'common': string;
  'exotic': string;
  'legendary': string;
  'movePopupDialog': string;
  'rare': string;
  'uncommon': string;
}
export const cssExports: CssExports;
export default cssExports;
