// This file is automatically generated.
// Please do not change this file!
export const disabled: string;
export const perkIconWrapper: string;
export const perkInfo: string;
export const plug: string;
export const plugLabel: string;
export const selected: string;
export const socket: string;
export const sockets: string;
