// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'itemTagSelector': string;
  'keyHelp': string;
  'minimized': string;
  'null': string;
}
export const cssExports: CssExports;
export default cssExports;
