// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'barContainer': string;
  'barInner': string;
  'icon': string;
  'masterworkStatBar': string;
  'masterworked': string;
  'modded': string;
  'moddedStatBar': string;
  'quality': string;
  'qualitySummary': string;
  'ratingChartBarColor': string;
  'statBar': string;
  'statName': string;
  'totalRow': string;
  'totalStatDetailed': string;
  'totalStatMasterwork': string;
  'totalStatModded': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
