// This file is automatically generated.
// Please do not change this file!
export const activated: string;
export const defaultValue: string;
export const nodeImg: string;
export const nodeXp: string;
export const showXp: string;
export const talentGrid: string;
