// This file is automatically generated.
// Please do not change this file!
export const arrow: string;
export const common: string;
export const desktopActions: string;
export const desktopPopup: string;
export const desktopPopupBody: string;
export const desktopPopupRoot: string;
export const exotic: string;
export const failureReason: string;
export const header: string;
export const legendary: string;
export const mobileItemActions: string;
export const mobileMoveLocations: string;
export const movePopupDialog: string;
export const popupBackground: string;
export const rare: string;
export const sheetClose: string;
export const sheetHeader: string;
export const uncommon: string;
