// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'perkIcon': string;
  'perkInfo': string;
  'plug': string;
  'plugLabel': string;
  'plugged': string;
  'selected': string;
  'socket': string;
  'sockets': string;
}
export const cssExports: CssExports;
export default cssExports;
