// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'archetype': string;
  'archetypeMod': string;
  'disabled': string;
  'mod': string;
  'perkIcon': string;
  'plug': string;
  'plugLabel': string;
  'plugged': string;
  'row': string;
  'socket': string;
  'sockets': string;
}
export const cssExports: CssExports;
export default cssExports;
