// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movePopupTab': string;
  'movePopupTabs': string;
  'selected': string;
}
export const cssExports: CssExports;
export = cssExports;
