// This file is automatically generated.
// Please do not change this file!
export const archetype: string;
export const displayStyleButton: string;
export const grid: string;
export const gridLines: string;
export const perks: string;
export const stats: string;
