// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'locations': string;
}
declare const cssExports: CssExports;
export = cssExports;
