// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activated': string;
  'default': string;
  'nodeImg': string;
  'nodeXp': string;
  'showXp': string;
  'talentGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
