// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'descriptionTools': string;
  'loreLink': string;
  'officialDescription': string;
  'wishListLabel': string;
  'wishListTextContent': string;
}
export const cssExports: CssExports;
export default cssExports;
