// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNotesLabel': string;
  'dropdownMenu': string;
  'editIcon': string;
  'error': string;
  'minimal': string;
  'noNotesYet': string;
  'notesLabel': string;
  'openNotesEditor': string;
}
export const cssExports: CssExports;
export default cssExports;
