// This file is automatically generated.
// Please do not change this file!
export const addNotesLabel: string;
export const editIcon: string;
export const error: string;
export const minimal: string;
export const noNotesYet: string;
export const notesLabel: string;
export const openNotesEditor: string;
