// This file is automatically generated.
// Please do not change this file!
export const cannotRoll: string;
export const disabled: string;
export const hasMenu: string;
export const masterwork: string;
export const mod: string;
export const none: string;
export const notSelected: string;
export const perkCircle: string;
export const perkOutline: string;
export const plug: string;
export const plugged: string;
export const selectable: string;
export const selected: string;
