// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'cannotRollSection': string;
  'clarityDescription': string;
  'communityInsightSection': string;
  'content': string;
  'control': string;
  'craftingRequirementsSection': string;
  'header': string;
  'minimalTooltip': string;
  'objectives': string;
  'perkName': string;
  'requirement': string;
  'section': string;
  'source': string;
  'tooltip': string;
  'wideTooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
