// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clarityDescription': string;
  'objectives': string;
  'perkName': string;
  'requirement': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
