// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cannotRoll': string;
  'disabled': string;
  'hasMenu': string;
  'mod': string;
  'none': string;
  'notSelected': string;
  'plugged': string;
  'selectable': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
