// This file is automatically generated.
// Please do not change this file!
export const activePerk: string;
export const gearList: string;
export const gearListIcon: string;
export const justCircle: string;
export const perk: string;
export const perkIcon: string;
export const perkNameSubheader: string;
export const setBonus: string;
export const setBonusesStatus: string;
export const unsatisfied: string;
