// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activePerk': string;
  'gearList': string;
  'gearListIcon': string;
  'justCircle': string;
  'perk': string;
  'perkIcon': string;
  'perkNameSubheader': string;
  'setBonus': string;
  'setBonusesStatus': string;
  'unsatisfied': string;
}
export const cssExports: CssExports;
export = cssExports;
