// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extraMargin': string;
  'perk': string;
  'perkIcon': string;
  'setBonus': string;
}
export const cssExports: CssExports;
export default cssExports;
