// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryIcon': string;
  'modList': string;
  'notUnlocked': string;
  'selected': string;
  'socketDetailsSheet': string;
}
declare const cssExports: CssExports;
export = cssExports;
