// This file is automatically generated.
// Please do not change this file!
export const categoryIcon: string;
export const clickableMod: string;
export const energyElement: string;
export const header: string;
export const modList: string;
export const notUnlocked: string;
export const selected: string;
export const socketDetailsSheet: string;
