// This file is automatically generated.
// Please do not change this file!
export const insertButton: string;
export const insertLabel: string;
export const itemStats: string;
export const material: string;
export const modClarityDescription: string;
export const modDescription: string;
export const modIcon: string;
export const modName: string;
export const modRequirement: string;
export const perk: string;
export const selectedPlug: string;
export const source: string;
