// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasStats': string;
  'insertButton': string;
  'insertLabel': string;
  'itemStats': string;
  'material': string;
  'modClarityDescription': string;
  'modDescription': string;
  'modIcon': string;
  'modStats': string;
  'selectedPlug': string;
  'source': string;
}
export const cssExports: CssExports;
export default cssExports;
