// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'catalystProgress': string;
  'catalystProgressTitle': string;
  'elementIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
