// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deepsightProgress': string;
  'deepsightProgressSection': string;
}
export const cssExports: CssExports;
export default cssExports;
