// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deepsightHarmonizableIcon': string;
  'deepsightProgress': string;
  'deepsightProgressBar': string;
}
export const cssExports: CssExports;
export default cssExports;
