// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityIcon': string;
  'activityItems': string;
  'bountyGuide': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
