// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applySearch': string;
  'message': string;
  'noSearches': string;
  'options': string;
}
export const cssExports: CssExports;
export default cssExports;
