// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapseTitle': string;
  'loadoutView': string;
}
export const cssExports: CssExports;
export default cssExports;
