// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activePursuits': string;
  'bountyGuide': string;
  'message': string;
  'noQuests': string;
}
export const cssExports: CssExports;
export default cssExports;
