// This file is automatically generated.
// Please do not change this file!
export const activities: string;
export const activityInfo: string;
export const activityType: string;
export const characters: string;
export const complete: string;
export const featured: string;
export const skullIcon: string;
export const skulls: string;
export const smallIcon: string;
export const stepIcon: string;
export const steps: string;
export const tierCharacters: string;
export const tierTitle: string;
export const title: string;
export const weak: string;
