// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activities': string;
  'activityInfo': string;
  'activityType': string;
  'characters': string;
  'complete': string;
  'featured': string;
  'skullIcon': string;
  'skulls': string;
  'smallIcon': string;
  'stepIcon': string;
  'steps': string;
  'tierCharacters': string;
  'tierTitle': string;
  'title': string;
  'weak': string;
}
export const cssExports: CssExports;
export default cssExports;
