// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bungieAlert': string;
  'error': string;
  'info': string;
  'warn': string;
}
export const cssExports: CssExports;
export = cssExports;
