// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badgeNew': string;
  'upgrade': string;
}
export const cssExports: CssExports;
export = cssExports;
