// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filters': string;
  'powerSelect': string;
  'row': string;
}
declare var cssExports: CssExports;
export = cssExports;
