// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altPerkKey': string;
  'key': string;
  'newLoadout': string;
  'numSets': string;
  'selectedPerkKey': string;
  'sets': string;
}
declare const cssExports: CssExports;
export = cssExports;
