// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'build': string;
  'header': string;
  'items': string;
  'light': string;
}
declare var cssExports: CssExports;
export = cssExports;
