// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'newLoadout': string;
  'numSets': string;
  'sets': string;
}
declare var cssExports: CssExports;
export = cssExports;
