// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altPerk': string;
  'item': string;
  'items': string;
}
declare var cssExports: CssExports;
export = cssExports;
