// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grip': string;
  'icon-Mobility': string;
  'icon-Recovery': string;
  'icon-Resilience': string;
  'iconMobility': string;
  'iconRecovery': string;
  'iconResilience': string;
  'iconStat': string;
}
declare var cssExports: CssExports;
export = cssExports;
