// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'file': string;
  'icon-Mobility': string;
  'icon-Recovery': string;
  'icon-Resilience': string;
  'iconMobility': string;
  'iconRecovery': string;
  'iconResilience': string;
  'iconStat': string;
  'mappings': string;
  'names': string;
  'sources': string;
  'sourcesContent': string;
  'version': string;
}
declare var cssExports: CssExports;
export = cssExports;
