// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'cta': string;
  'goal': string;
  'hero': string;
  'info': string;
  'issueAwarenessBanner': string;
  'item': string;
  'mercury': string;
  'thermo': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
