// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const cta: string;
export const goal: string;
export const hero: string;
export const info: string;
export const issueAwarenessBanner: string;
export const item: string;
export const mercury: string;
export const thermo: string;
export const track: string;
