// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'header': string;
  'headerInfo': string;
  'inspectRow': string;
  'itemImg': string;
  'mobileInspectSheet': string;
  'zoom': string;
}
export const cssExports: CssExports;
export default cssExports;
