// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'enter': string;
  'enterActive': string;
  'exit': string;
  'exitActive': string;
  'header': string;
  'headerInfo': string;
  'inspectActive': string;
  'inspectRow': string;
  'itemImg': string;
  'mobileInspectSheet': string;
  'moveLocations': string;
  'sheetBackground': string;
}
export const cssExports: CssExports;
export default cssExports;
