// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'floated': string;
  'thumb': string;
  'trashlist': string;
}
export const cssExports: CssExports;
export = cssExports;
