// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'guide': string;
  'loadoutEditSection': string;
  'menuContent': string;
  'page': string;
  'processing': string;
  'speedReport': string;
  'toolbar': string;
  'undoRedo': string;
}
export const cssExports: CssExports;
export default cssExports;
