// This file is automatically generated.
// Please do not change this file!
export const dismissButton: string;
export const fineprint: string;
export const guide: string;
export const header: string;
export const loadoutEditSection: string;
export const menuContent: string;
export const page: string;
export const referenceTiersInfo: string;
export const speedReport: string;
export const speedReportInner: string;
export const subclassSection: string;
export const toolbar: string;
export const undoRedo: string;
export const wide: string;
