// This file is automatically generated.
// Please do not change this file!
export const modRow: string;
export const noBuildsExplainerContainer: string;
export const noBuildsFoundMsg: string;
export const problemDescription: string;
export const suggestionList: string;
