// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modRow': string;
  'noBuildsExplainerContainer': string;
  'noBuildsFoundMsg': string;
  'problemDescription': string;
  'suggestionList': string;
}
export const cssExports: CssExports;
export = cssExports;
