// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'info': string;
  'itemGrid': string;
  'itemPickerItem': string;
  'title': string;
  'titleClassIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
