// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'lockedSockets': string;
  'lockedSocketsRow': string;
  'swapButton': string;
  'swapButtonContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
