// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'file': string;
  'frame': string;
  'horizontal': string;
  'mappings': string;
  'names': string;
  'pager': string;
  'select': string;
  'sources': string;
  'sourcesContent': string;
  'tile': string;
  'track': string;
  'unselected': string;
  'version': string;
  'vertical': string;
}
declare var cssExports: CssExports;
export = cssExports;
