// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'frame': string;
  'horizontal': string;
  'pager': string;
  'select': string;
  'tile': string;
  'track': string;
  'unselected': string;
  'vertical': string;
}
declare var cssExports: CssExports;
export = cssExports;
