// This file is automatically generated.
// Please do not change this file!
export const file: string;
export const horizontal: string;
export const mappings: string;
export const names: string;
export const select: string;
export const sources: string;
export const sourcesContent: string;
export const tile: string;
export const unselected: string;
export const version: string;
export const vertical: string;
