// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appIcon': string;
  'vendorMenuItem': string;
}
export const cssExports: CssExports;
export = cssExports;
