// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryTitle': string;
  'currencies': string;
  'currencyIcon': string;
  'itemCategories': string;
  'vendorContents': string;
  'vendorItems': string;
}
export const cssExports: CssExports;
export default cssExports;
