// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'glow': string;
  'icon': string;
  'location': string;
  'title': string;
  'titleDetails': string;
  'xyzActiveThrob': string;
  'xyzEngram': string;
}
declare const cssExports: CssExports;
export = cssExports;
