// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acquiredIcon': string;
  'attachedIcon': string;
  'attachedWeaponIcon': string;
  'cost': string;
  'currency': string;
  'notEnough': string;
  'ownedIcon': string;
  'ownershipIcon': string;
  'tile': string;
  'unavailable': string;
  'vendorCosts': string;
  'vendorItem': string;
}
declare const cssExports: CssExports;
export = cssExports;
