// This file is automatically generated.
// Please do not change this file!
export const categoryTitle: string;
export const currencies: string;
export const currencyIcon: string;
export const itemCategories: string;
export const vendorContents: string;
export const vendorItems: string;
