// This file is automatically generated.
// Please do not change this file!
export const countdown: string;
export const glow: string;
export const icon: string;
export const location: string;
export const title: string;
export const titleDetails: string;
