// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'countdown': string;
  'glow': string;
  'icon': string;
  'location': string;
  'title': string;
  'titleDetails': string;
}
export const cssExports: CssExports;
export = cssExports;
