// This file is automatically generated.
// Please do not change this file!
export const acquiredIcon: string;
export const cost: string;
export const lockedIcon: string;
export const ownedIcon: string;
export const ownershipIcon: string;
export const tile: string;
export const unavailable: string;
export const vendorItem: string;
