// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acquiredIcon': string;
  'cost': string;
  'lockedIcon': string;
  'ownedIcon': string;
  'ownershipIcon': string;
  'tile': string;
  'unavailable': string;
  'vendorItem': string;
}
export const cssExports: CssExports;
export = cssExports;
