// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'multiPerk': string;
  'perks': string;
  'stats': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
