// This file is automatically generated.
// Please do not change this file!
export const armorStats: string;
export const enhancedArrow: string;
export const multiPerk: string;
export const perk: string;
export const perks: string;
export const statRow: string;
export const stats: string;
export const type: string;
