// This file is automatically generated.
// Please do not change this file!
export const expanded: string;
export const sideTray: string;
export const trayButton: string;
export const trayContainer: string;
