// This file is automatically generated.
// Please do not change this file!
export const classIcon: string;
export const clearButton: string;
export const info: string;
export const item: string;
export const list: string;
export const title: string;
