// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tagButton': string;
  'tagButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
