// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'basic': string;
  'borderless': string;
  'common': string;
  'complete': string;
  'energyCost': string;
  'energyCostOverlay': string;
  'exotic': string;
  'exoticMasterwork': string;
  'iconOverlay': string;
  'legendary': string;
  'masterwork': string;
  'masterworkOverlay': string;
  'rare': string;
}
export const cssExports: CssExports;
export default cssExports;
