// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header': string;
  'item': string;
  'loadoutSelect': string;
  'set': string;
  'setHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
