// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'featuredHeader': string;
  'file': string;
  'mappings': string;
  'names': string;
  'sources': string;
  'sourcesContent': string;
  'version': string;
}
declare var cssExports: CssExports;
export = cssExports;
