// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'file': string;
  'icon': string;
  'location': string;
  'mappings': string;
  'names': string;
  'sources': string;
  'sourcesContent': string;
  'title': string;
  'titleDetails': string;
  'version': string;
}
declare var cssExports: CssExports;
export = cssExports;
