// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'location': string;
  'title': string;
  'titleDetails': string;
}
declare var cssExports: CssExports;
export = cssExports;
