// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkButton': string;
  'file': string;
  'mappings': string;
  'menu': string;
  'menuButton': string;
  'menuHeader': string;
  'names': string;
  'sources': string;
  'sourcesContent': string;
  'vendorResults': string;
  'vendors': string;
  'version': string;
}
declare var cssExports: CssExports;
export = cssExports;
