// This file is automatically generated.
// Please do not change this file!
export const categoryTitle: string;
export const currencies: string;
export const currency: string;
export const file: string;
export const itemCategories: string;
export const mappings: string;
export const names: string;
export const sources: string;
export const sourcesContent: string;
export const vendorContents: string;
export const vendorItems: string;
export const vendorRow: string;
export const version: string;
