// This file is automatically generated.
// Please do not change this file!
export const file: string;
export const icon: string;
export const location: string;
export const mappings: string;
export const names: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
