// This file is automatically generated.
// Please do not change this file!
export const file: string;
export const mappings: string;
export const menu: string;
export const menuButton: string;
export const menuHeader: string;
export const names: string;
export const sources: string;
export const sourcesContent: string;
export const vendorResults: string;
export const vendors: string;
export const version: string;
