// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryTitle': string;
  'currencies': string;
  'currency': string;
  'itemCategories': string;
  'vendorContents': string;
  'vendorItems': string;
  'vendorRow': string;
}
declare var cssExports: CssExports;
export = cssExports;
