// This file is automatically generated.
// Please do not change this file!
export const acquiredIcon: string;
export const cost: string;
export const currency: string;
export const file: string;
export const mappings: string;
export const names: string;
export const notEnough: string;
export const ownedIcon: string;
export const ownershipIcon: string;
export const sources: string;
export const sourcesContent: string;
export const tile: string;
export const unavailable: string;
export const vendorCosts: string;
export const vendorItem: string;
export const version: string;
