// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closedBar': string;
  'closedBarText': string;
  'content': string;
  'emblem': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
