// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityColumn': string;
  'activityInventory': string;
  'activitySplit': string;
  'bucketLabel': string;
  'collapsed': string;
}
export const cssExports: CssExports;
export default cssExports;
