// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alt': string;
  'beta': string;
  'inventoryToggle': string;
}
export const cssExports: CssExports;
export default cssExports;
