// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'frame': string;
  'tile': string;
  'track': string;
  'unselected': string;
  'vertical': string;
}
export const cssExports: CssExports;
export = cssExports;
