// This file is automatically generated.
// Please do not change this file!
export const frame: string;
export const tile: string;
export const track: string;
export const unselected: string;
export const vertical: string;
