// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'classSelect': string;
  'disabled': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
