// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'close': string;
  'container': string;
  'showCloseOnHover': string;
}
export const cssExports: CssExports;
export default cssExports;
