// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapseIcon': string;
  'collapsed': string;
  'content': string;
  'disabled': string;
  'iconCollapsed': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
