// This file is automatically generated.
// Please do not change this file!
export const collapsed: string;
export const collapseIcon: string;
export const content: string;
export const disabled: string;
export const iconCollapsed: string;
export const title: string;
