// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirmButton': string;
  'confirmMode': string;
}
export const cssExports: CssExports;
export = cssExports;
