// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'statWeightRow': string;
}
export const cssExports: CssExports;
export = cssExports;
