// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeStats': string;
  'inactiveStats': string;
  'inlineStatIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
