// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeStatLabels': string;
  'divider': string;
  'inactiveStatLabels': string;
  'inlineStatIcon': string;
  'readOnly': string;
}
export const cssExports: CssExports;
export default cssExports;
