// This file is automatically generated.
// Please do not change this file!
export const activeStatLabels: string;
export const divider: string;
export const inactiveStatLabels: string;
export const inlineStatIcon: string;
export const readOnly: string;
