// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'seasonalExpiration': string;
  'shapedIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
