// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'disabled': string;
  'highlighted': string;
  'kebabButton': string;
  'menu': string;
  'menuItem': string;
}
export const cssExports: CssExports;
export default cssExports;
