// This file is automatically generated.
// Please do not change this file!
export const arrow: string;
export const button: string;
export const disabled: string;
export const highlighted: string;
export const kebabButton: string;
export const menu: string;
export const menuItem: string;
export const separator: string;
