// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'energyMeterIncrements': string;
  'medium': string;
  'small': string;
  'unavailable': string;
  'unused': string;
  'used': string;
}
export const cssExports: CssExports;
export default cssExports;
