// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'open': string;
  'textBlockWrapper': string;
}
export const cssExports: CssExports;
export = cssExports;
