// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dragActive': string;
  'fileInput': string;
  'instructions': string;
}
export const cssExports: CssExports;
export = cssExports;
