// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'darkBackground': string;
  'guide': string;
  'pill': string;
  'selected': string;
}
export const cssExports: CssExports;
export = cssExports;
