// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'cancel': string;
  'input': string;
  'inputContainer': string;
  'inputModal': string;
  'label': string;
  'submit': string;
}
export const cssExports: CssExports;
export default cssExports;
