// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemPop': string;
  'pop': string;
}
export const cssExports: CssExports;
export default cssExports;
