// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'fadeIn': string;
  'loading': string;
  'logoAnimationPop': string;
  'square': string;
  'text': string;
  'textContainer': string;
}
export const cssExports: CssExports;
export = cssExports;
