// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const fadeIn: string;
export const loading: string;
export const logoAnimationPop: string;
export const square: string;
export const text: string;
export const textContainer: string;
