// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contents': string;
  'menu': string;
  'menuButton': string;
  'menuHeader': string;
  'menuScrollbars': string;
  'page': string;
}
export const cssExports: CssExports;
export default cssExports;
