// This file is automatically generated.
// Please do not change this file!
export const contents: string;
export const menu: string;
export const menuButton: string;
export const menuHeader: string;
export const menuScrollbars: string;
export const page: string;
