// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contents': string;
  'menu': string;
  'menuButton': string;
  'menuHeader': string;
  'page': string;
}
declare const cssExports: CssExports;
export = cssExports;
