// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'content': string;
  'control': string;
  'header': string;
  'minimalTooltip': string;
  'section': string;
  'tooltip': string;
  'wideTooltip': string;
}
export const cssExports: CssExports;
export = cssExports;
