// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'selected': string;
}
export const cssExports: CssExports;
export = cssExports;
