// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'button': string;
  'disabled': string;
  'highlighted': string;
  'menu': string;
  'menuItem': string;
  'open': string;
}
export const cssExports: CssExports;
export = cssExports;
