// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'container': string;
  'contents': string;
  'disabledScreen': string;
  'footer': string;
  'header': string;
  'noHeader': string;
  'sheet': string;
  'sheetDisabled': string;
}
export const cssExports: CssExports;
export = cssExports;
