// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabledScreen': string;
  'horizontalScroller': string;
  'sheetDisabled': string;
}
export const cssExports: CssExports;
export default cssExports;
