// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabledScreen': string;
  'noHeader': string;
  'sheetDisabled': string;
}
export const cssExports: CssExports;
export default cssExports;
