// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lowRes': string;
  'specialtyModIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
