// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'compact': string;
  'details': string;
  'disabled': string;
  'header': string;
  'items': string;
  'selected': string;
  'tile': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
