// This file is automatically generated.
// Please do not change this file!
export const compact: string;
export const details: string;
export const disabled: string;
export const header: string;
export const items: string;
export const selected: string;
export const tile: string;
export const title: string;
