// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'form': string;
  'preview': string;
  'radios': string;
}
export const cssExports: CssExports;
export = cssExports;
