// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checked': string;
  'form': string;
  'radio': string;
  'radios': string;
}
export const cssExports: CssExports;
export default cssExports;
