// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'buttons': string;
  'dialog': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
