// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentsPlaceholder': string;
  'scrollContainer': string;
  'virtualArea': string;
}
export const cssExports: CssExports;
export default cssExports;
