// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deepsightObjectiveProgress': string;
  'deepsightProgress': string;
}
export const cssExports: CssExports;
export default cssExports;
