// This file is automatically generated.
// Please do not change this file!
export const item: string;
export const locked: string;
export const stat: string;
export const tier: string;
export const tiers: string;
export const unlocked: string;
export const unlockedTier: string;
