// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'locked': string;
  'tier': string;
  'tiers': string;
  'unlocked': string;
}
export const cssExports: CssExports;
export default cssExports;
