// This file is automatically generated.
// Please do not change this file!
export const bookIcon: string;
export const complete: string;
export const hideCompleted: string;
export const record: string;
export const recordBook: string;
export const recordBookPage: string;
export const recordBooks: string;
export const recordIcon: string;
export const recordInfo: string;
export const records: string;
