// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookIcon': string;
  'complete': string;
  'hideCompleted': string;
  'record': string;
  'recordBook': string;
  'recordBookPage': string;
  'recordBooks': string;
  'recordIcon': string;
  'recordInfo': string;
  'records': string;
}
export const cssExports: CssExports;
export = cssExports;
