// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'prismatic': string;
  'stasis': string;
  'strand': string;
  'thermal': string;
  'void': string;
}
export const cssExports: CssExports;
export default cssExports;
