// This file is automatically generated.
// Please do not change this file!
export const arc: string;
export const prismatic: string;
export const stasis: string;
export const strand: string;
export const thermal: string;
export const voidColor: string;
