// This file is automatically generated.
// Please do not change this file!
export const buttonDiv: string;
export const emojiButton: string;
export const symbolsBody: string;
export const symbolsButton: string;
export const symbolsContainer: string;
export const symbolsFooter: string;
export const symbolsSearch: string;
export const symbolsWindow: string;
export const wrapperDiv: string;
