// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complete': string;
  'completed': string;
  'description': string;
  'goal': string;
  'hasProgressBar': string;
  'icon': string;
  'info': string;
  'masterworked': string;
  'metric': string;
  'name': string;
  'progressBar': string;
  'progressFill': string;
  'value': string;
}
export const cssExports: CssExports;
export = cssExports;
