// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metrics': string;
  'metricsGrid': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
