// This file is automatically generated.
// Please do not change this file!
export const description: string;
export const header: string;
export const icon: string;
export const masterworked: string;
export const metric: string;
export const name: string;
export const value: string;
