// This file is automatically generated.
// Please do not change this file!
export const bannerIcon: string;
export const icon: string;
export const metricIcon: string;
export const scopeIcon: string;
