// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nodeProgress': string;
  'nodeProgressBar': string;
  'nodeProgressBarAmount': string;
  'nodeProgressCount': string;
}
export const cssExports: CssExports;
export default cssExports;
