// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gildedNum': string;
  'gildedThisSeason': string;
  'incompleteTitleIcon': string;
  'isGilded': string;
  'nodeName': string;
  'nodeProgress': string;
  'nodeProgressBar': string;
  'nodeProgressBarAmount': string;
  'nodeProgressCount': string;
  'onlyChild': string;
}
export const cssExports: CssExports;
export default cssExports;
