// This file is automatically generated.
// Please do not change this file!
export const alwaysExpanded: string;
export const completed: string;
export const gildedNum: string;
export const gildedThisSeason: string;
export const incompleteTitleIcon: string;
export const isGilded: string;
export const nodeImg: string;
export const nodeProgress: string;
export const nodeProgressBar: string;
export const nodeProgressBarAmount: string;
export const onlyChild: string;
export const presentationNode: string;
