// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page': string;
  'presentationNodeOptions': string;
}
export const cssExports: CssExports;
export = cssExports;
