// This file is automatically generated.
// Please do not change this file!
export const complete: string;
export const currentScore: string;
export const dimTrackedIcon: string;
export const gildingText: string;
export const gildingTriumph: string;
export const glow: string;
export const icon: string;
export const info: string;
export const interval: string;
export const intervalContainer: string;
export const intervalRedeemed: string;
export const intervalUnlocked: string;
export const item: string;
export const multistep: string;
export const objectives: string;
export const obscured: string;
export const recordLore: string;
export const recordsGrid: string;
export const redeemed: string;
export const score: string;
export const tracked: string;
export const trackedIcon: string;
export const trackedInDim: string;
export const triumphRecord: string;
export const unlocked: string;
