// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complete': string;
  'currentScore': string;
  'dimTrackedIcon': string;
  'gildingText': string;
  'gildingTriumph': string;
  'icon': string;
  'info': string;
  'interval': string;
  'intervalContainer': string;
  'intervalRedeemed': string;
  'intervalUnlocked': string;
  'multistep': string;
  'objectives': string;
  'obscured': string;
  'recordLore': string;
  'redeemed': string;
  'score': string;
  'tracked': string;
  'trackedIcon': string;
  'trackedInDim': string;
  'triumphRecord': string;
  'unlocked': string;
}
export const cssExports: CssExports;
export default cssExports;
