// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'complete': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
