// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'buttons': string;
  'categoryArmor': string;
  'categoryGeneral': string;
  'categoryWeapons': string;
  'equippedGrid': string;
  'itemBucket': string;
  'itemCategory': string;
  'items': string;
  'itemsInCategory': string;
  'missingItem': string;
  'showFashion': string;
  'unequipped': string;
  'unequippedGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
