// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'contents': string;
  'mods': string;
  'modsStack': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
