// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'buttons': string;
  'canDrop': string;
  'categoryArmor': string;
  'categoryGeneral': string;
  'categoryWeapons': string;
  'equipped': string;
  'isOver': string;
  'itemBucket': string;
  'itemCategory': string;
  'items': string;
  'itemsInCategory': string;
  'missingItem': string;
  'unequipped': string;
}
export const cssExports: CssExports;
export = cssExports;
