// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classButton': string;
  'modsPlaceholder': string;
  'power': string;
  'subclass': string;
  'subclassContainer': string;
  'subclassMods': string;
}
export const cssExports: CssExports;
export default cssExports;
