// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dragOver': string;
  'drop': string;
  'dropContainer': string;
  'over': string;
}
export const cssExports: CssExports;
export default cssExports;
