// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canDrop': string;
  'classButton': string;
  'isOver': string;
}
export const cssExports: CssExports;
export = cssExports;
