// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artifactEditRow': string;
  'buttons': string;
  'clearButton': string;
  'contents': string;
  'mods': string;
  'section': string;
}
export const cssExports: CssExports;
export = cssExports;
