// This file is automatically generated.
// Please do not change this file!
export const buttons: string;
export const clearButton: string;
export const contents: string;
export const mods: string;
export const section: string;
