// Taken from The Traveler: https://github.com/alexanderwe/the-traveler/blob/master/src/enums.ts
// TODO: Autogenerate TS files from swagger APIs instead

/**
 * Enum for the Bungie membership type
 * @enum
 */
export enum BungieMembershipType {
  All = -1,
  Xbox = 1,
  PSN = 2,
  PC = 4,
  Bungie = 254,
}

/**
* Enum for Desinty component type
* @enum
*/
export enum ComponentType {
  None = 0,
  Profiles = 100,
  VendorReceipts = 101,
  ProfileInventories = 102,
  ProfileCurrencies = 103,
  Characters = 200,
  CharacterInventories = 201,
  CharacterProgressions = 202,
  CharacterRenderData = 203,
  CharacterActivities = 204,
  CharacterEquipment = 205,
  ItemInstances = 300,
  ItemObjectives = 301,
  ItemPerks = 302,
  ItemRenderData = 303,
  ItemStats = 304,
  ItemSockets = 305,
  ItemTalentGrids = 306,
  ItemCommonData = 307,
  ItemPlugStates = 308,
  Vendors = 400,
  VendorCategories = 401,
  VendorSales = 402,
  Kiosks = 500,
}

/**
* Enum for component privacy
* @enum
*/
export enum ComponentPrivacySetting {
  None = 0,
  Public = 1,
  Private = 2,
}

/**
* Enum for the damage type of items
* @enum
*/
export enum DamageType {
  None = 0,
  Kinetic = 1,
  Arc = 2,
  Thermal = 3,
  Void = 4,
  Raid = 5,
}

/**
* Enum for Destiny acitivity difficulty
* @enum
*/
export enum DestinyActivityDifficultyTier {
  Trivial = 0,
  Easy = 1,
  Normal = 2,
  Challenging = 3,
  Hard = 4,
  Brave = 5,
  AlmostImpossible = 6,
  Impossible = 7,
}

/**
* Enum for Destiny acitivity mode type
* @enum
*/
export enum DestinyActivityModeType {
  None = 0,
  Story = 2,
  Strike = 3,
  Raid = 4,
  AllPvP = 5,
  Patrol = 6,
  AllPvE = 7,
  Reserved9 = 9,
  Control = 10,
  Reserved11 = 11,
  Clash = 12,
  Reserved13 = 13,
  Reserved15 = 15,
  Nightfall = 16,
  HeroicNightfall = 17,
  AllStrikes = 18,
  IronBanner = 19,
  Reserved20 = 20,
  Reserved21 = 21,
  Reserved22 = 22,
  Reserved24 = 24,
  Reserved25 = 25,
  Reserved26 = 26,
  Reserved27 = 27,
  Reserved28 = 28,
  Reserved29 = 29,
  Reserved30 = 30,
  Supremacy = 31,
  Reserved32 = 32,
  Survival = 37,
  Countdown = 38,
  TrialsOfTheNine = 39,
  Social = 40,
}

/**
* Enum for classes in Destiny 2
* @enum
*/
export enum DestinyClass {
  Titan = 0,
  Hunter = 1,
  Warlock = 2,
  Unknown = 3,
}

/**
* A flags enumeration indicating the versions of the game that a given user has purchased.
* @enum
*/
export enum DestinyGameVersion {
  None = 0,
  Destiny2 = 1,
}
/**
* Enum for genders in Destiny 2
* @enum
*/
export enum DestinyGender {
  Male = 0,
  Female = 1,
  Unknown = 2,
}

/**
* Enum for races in Destiny
* @enum
*/
export enum DestinyRace {
  Human = 0,
  Awoken = 1,
  Exo = 2,
  Unknown = 3,
}

/**
* Enum for Destiny stats group type
* @enum
*/
export enum DestinyStatsGroupType {
  None = 0,
  General = 1,
  Weapons = 2,
  Medals = 3,
  ReservedGroups = 100,
  Leadboards = 101,
  Activity = 102,
  UniqueWeapon = 103,
  Internal = 104,
}

/**
* Enum for Destiny talent node states
* @enum
*/
export enum DestinyTalentNodeState {
  Invalid = 0,
  CanUpgrade = 1,
  NoPoints = 2,
  NoPrerequisites = 3,
  NoSteps = 4,
  NoUnlock = 5,
  NoMaterial = 6,
  NoGridLevel = 7,
  SwappingLocked = 8,
  MustSwap = 9,
  Complete = 10,
  Unknown = 11,
  CreationOnly = 12,
  Hidden = 13,
}

/**
* The reasons why an item cannot be equipped, if any. Many flags can be set, or "None" if
* @enum
*/
export enum EquipFailureReason {
  None = 0,
  ItemUnequippable = 1,
  temUniqueEquipRestricted = 2,
  ItemFailedUnlockCheck = 4,
  ItemFailedLevelCheck = 8,
  ItemNotOnCharacter = 16,
}

/**
* Enum for the item bind status
* @enum
*/
export enum ItemBindStatus {
  NotBound = 0,
  BoundToCharacter = 1,
  BoundToAccount = 2,
  BoundToGuild = 3,
}

/**
* Enum for the item location
* @enum
*/
export enum ItemLocation {
  Unknown = 0,
  Inventory = 1,
  Vault = 2,
  Vendor = 3,
  Postmaster = 4,
}

/**
* Enum for the item state
* @enum
*/
export enum ItemState {
  None = 0,
  Locked = 1,
  Tracked = 2,
}

/**
* Enum for Destiny period type
* @enum
*/
export enum PeriodType {
  None = 0,
  Daily = 1,
  AllTime = 2,
  Activity = 3,
}

/**
* Enum for the possible error codes
* @enum
*/
export enum PlatformErrorCodes {
  None = 0,
  Success = 1,
  TransportException = 2,
  UnhandledException = 3,
  NotImplemented = 4,
  SystemDisabled = 5,
  FailedToLoadAvailableLocalesConfiguration = 6,
  ParameterParseFailure = 7,
  ParameterInvalidRange = 8,
  BadRequest = 9,
  AuthenticationInvalid = 10,
  DataNotFound = 11,
  InsufficientPrivileges = 12,
  Duplicate = 13,
  UnknownSqlResult = 14,
  ValidationError = 15,
  ValidationMissingFieldError = 16,
  ValidationInvalidInputError = 17,
  InvalidParameters = 18,
  ParameterNotFound = 19,
  UnhandledHttpException = 20,
  NotFound = 21,
  WebAuthModuleAsyncFailed = 22,
  InvalidReturnValue = 23,
  UserBanned = 24,
  InvalidPostBody = 25,
  MissingPostBody = 26,
  ExternalServiceTimeout = 27,
  ValidationLengthError = 28,
  ValidationRangeError = 29,
  JsonDeserializationError = 30,
  ThrottleLimitExceeded = 31,
  ValidationTagError = 32,
  ValidationProfanityError = 33,
  ValidationUrlFormatError = 34,
  ThrottleLimitExceededMinutes = 35,
  ThrottleLimitExceededMomentarily = 36,
  ThrottleLimitExceededSeconds = 37,
  ExternalServiceUnknown = 38,
  ValidationWordLengthError = 39,
  ValidationInvisibleUnicode = 40,
  ValidationBadNames = 41,
  ExternalServiceFailed = 42,
  ServiceRetired = 43,
  UnknownSqlException = 44,
  UnsupportedLocale = 45,
  InvalidPageNumber = 46,
  MaximumPageSizeExceeded = 47,
  ServiceUnsupported = 48,
  ValidationMaximumUnicodeCombiningCharacters = 49,
  ValidationMaximumSequentialCarriageReturns = 50,
  PerEndpointRequestThrottleExceeded = 51,
  AuthContextCacheAssertion = 52,
  ObsoleteCredentialType = 89,
  UnableToUnPairMobileApp = 90,
  UnableToPairMobileApp = 91,
  CannotUseMobileAuthWithNonMobileProvider = 92,
  MissingDeviceCookie = 93,
  FacebookTokenExpired = 94,
  AuthTicketRequired = 95,
  CookieContextRequired = 96,
  UnknownAuthenticationError = 97,
  BungieNetAccountCreationRequired = 98,
  WebAuthRequired = 99,
  ContentUnknownSqlResult = 100,
  ContentNeedUniquePath = 101,
  ContentSqlException = 102,
  ContentNotFound = 103,
  ContentSuccessWithTagAddFail = 104,
  ContentSearchMissingParameters = 105,
  ContentInvalidId = 106,
  ContentPhysicalFileDeletionError = 107,
  ContentPhysicalFileCreationError = 108,
  ContentPerforceSubmissionError = 109,
  ContentPerforceInitializationError = 110,
  ContentDeploymentPackageNotReadyError = 111,
  ContentUploadFailed = 112,
  ContentTooManyResults = 113,
  ContentInvalidState = 115,
  ContentNavigationParentNotFound = 116,
  ContentNavigationParentUpdateError = 117,
  DeploymentPackageNotEditable = 118,
  ContentValidationError = 119,
  ContentPropertiesValidationError = 120,
  ContentTypeNotFound = 121,
  DeploymentPackageNotFound = 122,
  ContentSearchInvalidParameters = 123,
  ContentItemPropertyAggregationError = 124,
  DeploymentPackageFileNotFound = 125,
  ContentPerforceFileHistoryNotFound = 126,
  ContentAssetZipCreationFailure = 127,
  ContentAssetZipCreationBusy = 128,
  ContentProjectNotFound = 129,
  ContentFolderNotFound = 130,
  ContentPackagesInconsistent = 131,
  ContentPackagesInvalidState = 132,
  ContentPackagesInconsistentType = 133,
  ContentCannotDeletePackage = 134,
  ContentLockedForChanges = 135,
  ContentFileUploadFailed = 136,
  ContentNotReviewed = 137,
  ContentPermissionDenied = 138,
  ContentInvalidExternalUrl = 139,
  ContentExternalFileCannotBeImportedLocally = 140,
  ContentTagSaveFailure = 141,
  ContentPerforceUnmatchedFileError = 142,
  ContentPerforceChangelistResultNotFound = 143,
  ContentPerforceChangelistFileItemsNotFound = 144,
  ContentPerforceInvalidRevisionError = 145,
  ContentUnloadedSaveResult = 146,
  ContentPropertyInvalidNumber = 147,
  ContentPropertyInvalidUrl = 148,
  ContentPropertyInvalidDate = 149,
  ContentPropertyInvalidSet = 150,
  ContentPropertyCannotDeserialize = 151,
  ContentRegexValidationFailOnProperty = 152,
  ContentMaxLengthFailOnProperty = 153,
  ContentPropertyUnexpectedDeserializationError = 154,
  ContentPropertyRequired = 155,
  ContentCannotCreateFile = 156,
  ContentInvalidMigrationFile = 157,
  ContentMigrationAlteringProcessedItem = 158,
  ContentPropertyDefinitionNotFound = 159,
  ContentReviewDataChanged = 160,
  ContentRollbackRevisionNotInPackage = 161,
  ContentItemNotBasedOnLatestRevision = 162,
  ContentUnauthorized = 163,
  ContentCannotCreateDeploymentPackage = 164,
  ContentUserNotFound = 165,
  ContentLocalePermissionDenied = 166,
  ContentInvalidLinkToInternalEnvironment = 167,
  ContentInvalidBlacklistedContent = 168,
  ContentMacroMalformedNoContentId = 169,
  ContentMacroMalformedNoTemplateType = 170,
  ContentIllegalBNetMembershipId = 171,
  ContentLocaleDidNotMatchExpected = 172,
  ContentBabelCallFailed = 173,
  ContentEnglishPostLiveForbidden = 174,
  ContentLocaleEditPermissionDenied = 175,
  UserNonUniqueName = 200,
  UserManualLinkingStepRequired = 201,
  UserCreateUnknownSqlResult = 202,
  UserCreateUnknownSqlException = 203,
  UserMalformedMembershipId = 204,
  UserCannotFindRequestedUser = 205,
  UserCannotLoadAccountCredentialLinkInfo = 206,
  UserInvalidMobileAppType = 207,
  UserMissingMobilePairingInfo = 208,
  UserCannotGenerateMobileKeyWhileUsingMobileCredential = 209,
  UserGenerateMobileKeyExistingSlotCollision = 210,
  UserDisplayNameMissingOrInvalid = 211,
  UserCannotLoadAccountProfileData = 212,
  UserCannotSaveUserProfileData = 213,
  UserEmailMissingOrInvalid = 214,
  UserTermsOfUseRequired = 215,
  UserCannotCreateNewAccountWhileLoggedIn = 216,
  UserCannotResolveCentralAccount = 217,
  UserInvalidAvatar = 218,
  UserMissingCreatedUserResult = 219,
  UserCannotChangeUniqueNameYet = 220,
  UserCannotChangeDisplayNameYet = 221,
  UserCannotChangeEmail = 222,
  UserUniqueNameMustStartWithLetter = 223,
  UserNoLinkedAccountsSupportFriendListings = 224,
  UserAcknowledgmentTableFull = 225,
  UserCreationDestinyMembershipRequired = 226,
  UserFriendsTokenNeedsRefresh = 227,
  MessagingUnknownError = 300,
  MessagingSelfError = 301,
  MessagingSendThrottle = 302,
  MessagingNoBody = 303,
  MessagingTooManyUsers = 304,
  MessagingCanNotLeaveConversation = 305,
  MessagingUnableToSend = 306,
  MessagingDeletedUserForbidden = 307,
  MessagingCannotDeleteExternalConversation = 308,
  MessagingGroupChatDisabled = 309,
  MessagingMustIncludeSelfInPrivateMessage = 310,
  MessagingSenderIsBanned = 311,
  MessagingGroupOptionalChatExceededMaximum = 312,
  AddSurveyAnswersUnknownSqlException = 400,
  ForumBodyCannotBeEmpty = 500,
  ForumSubjectCannotBeEmptyOnTopicPost = 501,
  ForumCannotLocateParentPost = 502,
  ForumThreadLockedForReplies = 503,
  ForumUnknownSqlResultDuringCreatePost = 504,
  ForumUnknownTagCreationError = 505,
  ForumUnknownSqlResultDuringTagItem = 506,
  ForumUnknownExceptionCreatePost = 507,
  ForumQuestionMustBeTopicPost = 508,
  ForumExceptionDuringTagSearch = 509,
  ForumExceptionDuringTopicRetrieval = 510,
  ForumAliasedTagError = 511,
  ForumCannotLocateThread = 512,
  ForumUnknownExceptionEditPost = 513,
  ForumCannotLocatePost = 514,
  ForumUnknownExceptionGetOrCreateTags = 515,
  ForumEditPermissionDenied = 516,
  ForumUnknownSqlResultDuringTagIdRetrieval = 517,
  ForumCannotGetRating = 518,
  ForumUnknownExceptionGetRating = 519,
  ForumRatingsAccessError = 520,
  ForumRelatedPostAccessError = 521,
  ForumLatestReplyAccessError = 522,
  ForumUserStatusAccessError = 523,
  ForumAuthorAccessError = 524,
  ForumGroupAccessError = 525,
  ForumUrlExpectedButMissing = 526,
  ForumRepliesCannotBeEmpty = 527,
  ForumRepliesCannotBeInDifferentGroups = 528,
  ForumSubTopicCannotBeCreatedAtThisThreadLevel = 529,
  ForumCannotCreateContentTopic = 530,
  ForumTopicDoesNotExist = 531,
  ForumContentCommentsNotAllowed = 532,
  ForumUnknownSqlResultDuringEditPost = 533,
  ForumUnknownSqlResultDuringGetPost = 534,
  ForumPostValidationBadUrl = 535,
  ForumBodyTooLong = 536,
  ForumSubjectTooLong = 537,
  ForumAnnouncementNotAllowed = 538,
  ForumCannotShareOwnPost = 539,
  ForumEditNoOp = 540,
  ForumUnknownDatabaseErrorDuringGetPost = 541,
  ForumExceeedMaximumRowLimit = 542,
  ForumCannotSharePrivatePost = 543,
  ForumCannotCrossPostBetweenGroups = 544,
  ForumIncompatibleCategories = 555,
  ForumCannotUseTheseCategoriesOnNonTopicPost = 556,
  ForumCanOnlyDeleteTopics = 557,
  ForumDeleteSqlException = 558,
  ForumDeleteSqlUnknownResult = 559,
  ForumTooManyTags = 560,
  ForumCanOnlyRateTopics = 561,
  ForumBannedPostsCannotBeEdited = 562,
  ForumThreadRootIsBanned = 563,
  ForumCannotUseOfficialTagCategoryAsTag = 564,
  ForumAnswerCannotBeMadeOnCreatePost = 565,
  ForumAnswerCannotBeMadeOnEditPost = 566,
  ForumAnswerPostIdIsNotADirectReplyOfQuestion = 567,
  ForumAnswerTopicIdIsNotAQuestion = 568,
  ForumUnknownExceptionDuringMarkAnswer = 569,
  ForumUnknownSqlResultDuringMarkAnswer = 570,
  ForumCannotRateYourOwnPosts = 571,
  ForumPollsMustBeTheFirstPostInTopic = 572,
  ForumInvalidPollInput = 573,
  ForumGroupAdminEditNonMember = 574,
  ForumCannotEditModeratorEditedPost = 575,
  ForumRequiresDestinyMembership = 576,
  ForumUnexpectedError = 577,
  ForumAgeLock = 578,
  ForumMaxPages = 579,
  ForumMaxPagesOldestFirst = 580,
  ForumCannotApplyForumIdWithoutTags = 581,
  ForumCannotApplyForumIdToNonTopics = 582,
  ForumCannotDownvoteCommunityCreations = 583,
  ForumTopicsMustHaveOfficialCategory = 584,
  ForumRecruitmentTopicMalformed = 585,
  ForumRecruitmentTopicNotFound = 586,
  ForumRecruitmentTopicNoSlotsRemaining = 587,
  ForumRecruitmentTopicKickBan = 588,
  ForumRecruitmentTopicRequirementsNotMet = 589,
  ForumRecruitmentTopicNoPlayers = 590,
  ForumRecruitmentApproveFailMessageBan = 591,
  ForumRecruitmentGlobalBan = 592,
  ForumUserBannedFromThisTopic = 593,
  ForumRecruitmentFireteamMembersOnly = 594,
  GroupMembershipApplicationAlreadyResolved = 601,
  GroupMembershipAlreadyApplied = 602,
  GroupMembershipInsufficientPrivileges = 603,
  GroupIdNotReturnedFromCreation = 604,
  GroupSearchInvalidParameters = 605,
  GroupMembershipPendingApplicationNotFound = 606,
  GroupInvalidId = 607,
  GroupInvalidMembershipId = 608,
  GroupInvalidMembershipType = 609,
  GroupMissingTags = 610,
  GroupMembershipNotFound = 611,
  GroupInvalidRating = 612,
  GroupUserFollowingAccessError = 613,
  GroupUserMembershipAccessError = 614,
  GroupCreatorAccessError = 615,
  GroupAdminAccessError = 616,
  GroupPrivatePostNotViewable = 617,
  GroupMembershipNotLoggedIn = 618,
  GroupNotDeleted = 619,
  GroupUnknownErrorUndeletingGroup = 620,
  GroupDeleted = 621,
  GroupNotFound = 622,
  GroupMemberBanned = 623,
  GroupMembershipClosed = 624,
  GroupPrivatePostOverrideError = 625,
  GroupNameTaken = 626,
  GroupDeletionGracePeriodExpired = 627,
  GroupCannotCheckBanStatus = 628,
  GroupMaximumMembershipCountReached = 629,
  NoDestinyAccountForClanPlatform = 630,
  AlreadyRequestingMembershipForClanPlatform = 631,
  AlreadyClanMemberOnPlatform = 632,
  GroupJoinedCannotSetClanName = 633,
  GroupLeftCannotClearClanName = 634,
  GroupRelationshipRequestPending = 635,
  GroupRelationshipRequestBlocked = 636,
  GroupRelationshipRequestNotFound = 637,
  GroupRelationshipBlockNotFound = 638,
  GroupRelationshipNotFound = 639,
  GroupAlreadyAllied = 641,
  GroupAlreadyMember = 642,
  GroupRelationshipAlreadyExists = 643,
  InvalidGroupTypesForRelationshipRequest = 644,
  GroupAtMaximumAlliances = 646,
  GroupCannotSetClanOnlySettings = 647,
  ClanCannotSetTwoDefaultPostTypes = 648,
  GroupMemberInvalidMemberType = 649,
  GroupInvalidPlatformType = 650,
  GroupMemberInvalidSort = 651,
  GroupInvalidResolveState = 652,
  ClanAlreadyEnabledForPlatform = 653,
  ClanNotEnabledForPlatform = 654,
  ClanEnabledButCouldNotJoinNoAccount = 655,
  ClanEnabledButCouldNotJoinAlreadyMember = 656,
  ClanCannotJoinNoCredential = 657,
  NoClanMembershipForPlatform = 658,
  GroupToGroupFollowLimitReached = 659,
  ChildGroupAlreadyInAlliance = 660,
  OwnerGroupAlreadyInAlliance = 661,
  AllianceOwnerCannotJoinAlliance = 662,
  GroupNotInAlliance = 663,
  ChildGroupCannotInviteToAlliance = 664,
  GroupToGroupAlreadyFollowed = 665,
  GroupToGroupNotFollowing = 666,
  ClanMaximumMembershipReached = 667,
  ClanNameNotValid = 668,
  ClanNameNotValidError = 669,
  AllianceOwnerNotDefined = 670,
  AllianceChildNotDefined = 671,
  ClanCultureIllegalCharacters = 672,
  ClanTagIllegalCharacters = 673,
  ClanRequiresInvitation = 674,
  ClanMembershipClosed = 675,
  ClanInviteAlreadyMember = 676,
  GroupInviteAlreadyMember = 677,
  GroupJoinApprovalRequired = 678,
  ClanTagRequired = 679,
  GroupNameCannotStartOrEndWithWhiteSpace = 680,
  ClanCallsignCannotStartOrEndWithWhiteSpace = 681,
  ClanMigrationFailed = 682,
  ClanNotEnabledAlreadyMemberOfAnotherClan = 683,
  GroupModerationNotPermittedOnNonMembers = 684,
  ClanCreationInWorldServerFailed = 685,
  ClanNotFound = 686,
  ClanMembershipLevelDoesNotPermitThatAction = 687,
  ClanMemberNotFound = 688,
  ClanMissingMembershipApprovers = 689,
  ClanInWrongStateForRequestedAction = 690,
  ClanNameAlreadyUsed = 691,
  ClanTooFewMembers = 692,
  ClanInfoCannotBeWhitespace = 693,
  GroupCultureThrottle = 694,
  ClanTargetDisallowsInvites = 695,
  ClanInvalidOperation = 696,
  ClanFounderCannotLeaveWithoutAbdication = 697,
  ClanNameReserved = 698,
  ClanApplicantInClanSoNowInvited = 699,
  ActivitiesUnknownException = 701,
  ActivitiesParameterNull = 702,
  ActivityCountsDiabled = 703,
  ActivitySearchInvalidParameters = 704,
  ActivityPermissionDenied = 705,
  ShareAlreadyShared = 706,
  ActivityLoggingDisabled = 707,
  ItemAlreadyFollowed = 801,
  ItemNotFollowed = 802,
  CannotFollowSelf = 803,
  GroupFollowLimitExceeded = 804,
  TagFollowLimitExceeded = 805,
  UserFollowLimitExceeded = 806,
  FollowUnsupportedEntityType = 807,
  NoValidTagsInList = 900,
  BelowMinimumSuggestionLength = 901,
  CannotGetSuggestionsOnMultipleTagsSimultaneously = 902,
  NotAValidPartialTag = 903,
  TagSuggestionsUnknownSqlResult = 904,
  TagsUnableToLoadPopularTagsFromDatabase = 905,
  TagInvalid = 906,
  TagNotFound = 907,
  SingleTagExpected = 908,
  TagsExceededMaximumPerItem = 909,
  IgnoreInvalidParameters = 1000,
  IgnoreSqlException = 1001,
  IgnoreErrorRetrievingGroupPermissions = 1002,
  IgnoreErrorInsufficientPermission = 1003,
  IgnoreErrorRetrievingItem = 1004,
  IgnoreCannotIgnoreSelf = 1005,
  IgnoreIllegalType = 1006,
  IgnoreNotFound = 1007,
  IgnoreUserGloballyIgnored = 1008,
  IgnoreUserIgnored = 1009,
  NotificationSettingInvalid = 1100,
  PsnApiExpiredAccessToken = 1204,
  PSNExForbidden = 1205,
  PSNExSystemDisabled = 1218,
  PsnApiErrorCodeUnknown = 1223,
  PsnApiErrorWebException = 1224,
  PsnApiBadRequest = 1225,
  PsnApiAccessTokenRequired = 1226,
  PsnApiInvalidAccessToken = 1227,
  PsnApiBannedUser = 1229,
  PsnApiAccountUpgradeRequired = 1230,
  PsnApiServiceTemporarilyUnavailable = 1231,
  PsnApiServerBusy = 1232,
  PsnApiUnderMaintenance = 1233,
  PsnApiProfileUserNotFound = 1234,
  PsnApiProfilePrivacyRestriction = 1235,
  PsnApiProfileUnderMaintenance = 1236,
  PsnApiAccountAttributeMissing = 1237,
  XblExSystemDisabled = 1300,
  XblExUnknownError = 1301,
  XblApiErrorWebException = 1302,
  XblStsTokenInvalid = 1303,
  XblStsMissingToken = 1304,
  XblStsExpiredToken = 1305,
  XblAccessToTheSandboxDenied = 1306,
  XblMsaResponseMissing = 1307,
  XblMsaAccessTokenExpired = 1308,
  XblMsaInvalidRequest = 1309,
  XblMsaFriendsRequireSignIn = 1310,
  XblUserActionRequired = 1311,
  XblParentalControls = 1312,
  XblDeveloperAccount = 1313,
  XblUserTokenExpired = 1314,
  XblUserTokenInvalid = 1315,
  XblOffline = 1316,
  XblUnknownErrorCode = 1317,
  XblMsaInvalidGrant = 1318,
  ReportNotYetResolved = 1400,
  ReportOverturnDoesNotChangeDecision = 1401,
  ReportNotFound = 1402,
  ReportAlreadyReported = 1403,
  ReportInvalidResolution = 1404,
  ReportNotAssignedToYou = 1405,
  LegacyGameStatsSystemDisabled = 1500,
  LegacyGameStatsUnknownError = 1501,
  LegacyGameStatsMalformedSneakerNetCode = 1502,
  DestinyAccountAcquisitionFailure = 1600,
  DestinyAccountNotFound = 1601,
  DestinyBuildStatsDatabaseError = 1602,
  DestinyCharacterStatsDatabaseError = 1603,
  DestinyPvPStatsDatabaseError = 1604,
  DestinyPvEStatsDatabaseError = 1605,
  DestinyGrimoireStatsDatabaseError = 1606,
  DestinyStatsParameterMembershipTypeParseError = 1607,
  DestinyStatsParameterMembershipIdParseError = 1608,
  DestinyStatsParameterRangeParseError = 1609,
  DestinyStringItemHashNotFound = 1610,
  DestinyStringSetNotFound = 1611,
  DestinyContentLookupNotFoundForKey = 1612,
  DestinyContentItemNotFound = 1613,
  DestinyContentSectionNotFound = 1614,
  DestinyContentPropertyNotFound = 1615,
  DestinyContentConfigNotFound = 1616,
  DestinyContentPropertyBucketValueNotFound = 1617,
  DestinyUnexpectedError = 1618,
  DestinyInvalidAction = 1619,
  DestinyCharacterNotFound = 1620,
  DestinyInvalidFlag = 1621,
  DestinyInvalidRequest = 1622,
  DestinyItemNotFound = 1623,
  DestinyInvalidCustomizationChoices = 1624,
  DestinyVendorItemNotFound = 1625,
  DestinyInternalError = 1626,
  DestinyVendorNotFound = 1627,
  DestinyRecentActivitiesDatabaseError = 1628,
  DestinyItemBucketNotFound = 1629,
  DestinyInvalidMembershipType = 1630,
  DestinyVersionIncompatibility = 1631,
  DestinyItemAlreadyInInventory = 1632,
  DestinyBucketNotFound = 1633,
  DestinyCharacterNotInTower = 1634,
  DestinyCharacterNotLoggedIn = 1635,
  DestinyDefinitionsNotLoaded = 1636,
  DestinyInventoryFull = 1637,
  DestinyItemFailedLevelCheck = 1638,
  DestinyItemFailedUnlockCheck = 1639,
  DestinyItemUnequippable = 1640,
  DestinyItemUniqueEquipRestricted = 1641,
  DestinyNoRoomInDestination = 1642,
  DestinyServiceFailure = 1643,
  DestinyServiceRetired = 1644,
  DestinyTransferFailed = 1645,
  DestinyTransferNotFoundForSourceBucket = 1646,
  DestinyUnexpectedResultInVendorTransferCheck = 1647,
  DestinyUniquenessViolation = 1648,
  DestinyErrorDeserializationFailure = 1649,
  DestinyValidAccountTicketRequired = 1650,
  DestinyShardRelayClientTimeout = 1651,
  DestinyShardRelayProxyTimeout = 1652,
  DestinyPGCRNotFound = 1653,
  DestinyAccountMustBeOffline = 1654,
  DestinyCanOnlyEquipInGame = 1655,
  DestinyCannotPerformActionOnEquippedItem = 1656,
  DestinyQuestAlreadyCompleted = 1657,
  DestinyQuestAlreadyTracked = 1658,
  DestinyTrackableQuestsFull = 1659,
  DestinyItemNotTransferrable = 1660,
  DestinyVendorPurchaseNotAllowed = 1661,
  DestinyContentVersionMismatch = 1662,
  DestinyItemActionForbidden = 1663,
  DestinyRefundInvalid = 1664,
  DestinyPrivacyRestriction = 1665,
  DestinyActionInsufficientPrivileges = 1666,
  DestinyInvalidClaimException = 1667,
  DestinyLegacyPlatformRestricted = 1668,
  DestinyLegacyPlatformInUse = 1669,
  DestinyLegacyPlatformInaccessible = 1670,
  DestinyCannotPerformActionAtThisLocation = 1671,
  DestinyThrottledByGameServer = 1672,
  FbInvalidRequest = 1800,
  FbRedirectMismatch = 1801,
  FbAccessDenied = 1802,
  FbUnsupportedResponseType = 1803,
  FbInvalidScope = 1804,
  FbUnsupportedGrantType = 1805,
  FbInvalidGrant = 1806,
  InvitationExpired = 1900,
  InvitationUnknownType = 1901,
  InvitationInvalidResponseStatus = 1902,
  InvitationInvalidType = 1903,
  InvitationAlreadyPending = 1904,
  InvitationInsufficientPermission = 1905,
  InvitationInvalidCode = 1906,
  InvitationInvalidTargetState = 1907,
  InvitationCannotBeReactivated = 1908,
  InvitationNoRecipients = 1910,
  InvitationGroupCannotSendToSelf = 1911,
  InvitationTooManyRecipients = 1912,
  InvitationInvalid = 1913,
  InvitationNotFound = 1914,
  TokenInvalid = 2000,
  TokenBadFormat = 2001,
  TokenAlreadyClaimed = 2002,
  TokenAlreadyClaimedSelf = 2003,
  TokenThrottling = 2004,
  TokenUnknownRedemptionFailure = 2005,
  TokenPurchaseClaimFailedAfterTokenClaimed = 2006,
  TokenUserAlreadyOwnsOffer = 2007,
  TokenInvalidOfferKey = 2008,
  TokenEmailNotValidated = 2009,
  TokenProvisioningBadVendorOrOffer = 2010,
  TokenPurchaseHistoryUnknownError = 2011,
  TokenThrottleStateUnknownError = 2012,
  TokenUserAgeNotVerified = 2013,
  TokenExceededOfferMaximum = 2014,
  TokenNoAvailableUnlocks = 2015,
  TokenMarketplaceInvalidPlatform = 2016,
  TokenNoMarketplaceCodesFound = 2017,
  TokenOfferNotAvailableForRedemption = 2018,
  TokenUnlockPartialFailure = 2019,
  TokenMarketplaceInvalidRegion = 2020,
  TokenOfferExpired = 2021,
  RAFExceededMaximumReferrals = 2022,
  RAFDuplicateBond = 2023,
  RAFNoValidVeteranDestinyMembershipsFound = 2024,
  RAFNotAValidVeteranUser = 2025,
  RAFCodeAlreadyClaimedOrNotFound = 2026,
  RAFMismatchedDestinyMembershipType = 2027,
  RAFUnableToAccessPurchaseHistory = 2028,
  RAFUnableToCreateBond = 2029,
  RAFUnableToFindBond = 2030,
  RAFUnableToRemoveBond = 2031,
  RAFCannotBondToSelf = 2032,
  RAFInvalidPlatform = 2033,
  RAFGenerateThrottled = 2034,
  RAFUnableToCreateBondVersionMismatch = 2035,
  RAFUnableToRemoveBondVersionMismatch = 2036,
  RAFRedeemThrottled = 2037,
  NoAvailableDiscountCode = 2038,
  DiscountAlreadyClaimed = 2039,
  DiscountClaimFailure = 2040,
  DiscountConfigurationFailure = 2041,
  DiscountGenerationFailure = 2042,
  DiscountAlreadyExists = 2043,
  TokenRequiresCredentialXuid = 2044,
  TokenRequiresCredentialPsnid = 2045,
  OfferRequired = 2046,
  ApiExceededMaxKeys = 2100,
  ApiInvalidOrExpiredKey = 2101,
  ApiKeyMissingFromRequest = 2102,
  ApplicationDisabled = 2103,
  ApplicationExceededMax = 2104,
  ApplicationDisallowedByScope = 2105,
  AuthorizationCodeInvalid = 2106,
  OriginHeaderDoesNotMatchKey = 2107,
  AccessNotPermittedByApplicationScope = 2108,
  ApplicationNameIsTaken = 2109,
  RefreshTokenNotYetValid = 2110,
  AccessTokenHasExpired = 2111,
  ApplicationTokenFormatNotValid = 2112,
  ApplicationNotConfiguredForBungieAuth = 2113,
  ApplicationNotConfiguredForOAuth = 2114,
  OAuthAccessTokenExpired = 2115,
  PartnershipInvalidType = 2200,
  PartnershipValidationError = 2201,
  PartnershipValidationTimeout = 2202,
  PartnershipAccessFailure = 2203,
  PartnershipAccountInvalid = 2204,
  PartnershipGetAccountInfoFailure = 2205,
  PartnershipDisabled = 2206,
  PartnershipAlreadyExists = 2207,
  CommunityStreamingUnavailable = 2300,
  TwitchNotLinked = 2500,
  TwitchAccountNotFound = 2501,
  TwitchCouldNotLoadDestinyInfo = 2502,
  TrendingCategoryNotFound = 2600,
  TrendingEntryTypeNotSupported = 2601,
}

/**
* Enum for different stat category types
* @enum
*/
export enum StatsCategoryType {
  None = 0,
  Kills = 1,
  Assists = 2,
  Deaths = 3,
  Criticals = 4,
  KDa = 5,
  KD = 6,
  Score = 7,
  Entered = 8,
  TimePlayed = 9,
  MedalWins = 10,
  MedalGame = 11,
  MedalSpecialKills = 12,
  MedalSprees = 13,
  MedalMultiKills = 14,
  MedalAbilities = 15,
}

/**
* Enum for different stat IDs
* @enum
*/
export enum StatId {
  ActivitiesClearedabilityKills = 'DestinyInventoryItemDefinition',
  ActivitiesEntered = 'ActivitiesEntered',
  ActivitiesWon = 'ActivitiesWon',
  Assists = 'Assists',
  AverageDeathDistance = 'AverageDeathDistance',
  AverageKillDistance = 'AverageKillDistance',
  AverageLifespan = 'AverageLifespan',
  AverageScorePerKill = 'AverageScorePerKill',
  AverageScorePerLife = 'AverageScorePerLife',
  BestSingleGameKills = 'BestSingleGameKills',
  BestSingleGameScore = 'BestSingleGameScore',
  Completed = 'Completed',
  FastestCompletionMsForActivity = 'FastestCompletionMsForActivity',
  ActivityCompletions = 'ActivityCompletions',
  ActivityDeaths = 'ActivityDeaths',
  ActivityKills = 'ActivityKills',
  ActivitySecondsPlayed = 'ActivitySecondsPlayed',
  ActivityWins = 'ActivityWins',
  ActivityGoalsMissed = 'ActivityGoalsMissed',
  ActivityCompletedFailures = 'ActivityCompletedFailures',
  ActivitySpecialActions = 'ActivitySpecialActions',
  ActivityBestGoalsHit = 'ActivityBestGoalsHit',
  ActivitySpecialScore = 'ActivitySpecialScore',
  ActivityFastestObjectiveCompletionMs = 'ActivityFastestObjectiveCompletionMs',
  ActivityBestSingleGameScore = 'ActivityBestSingleGameScore',
  ActivityKillsDeathsRatio = 'ActivityKillsDeathsRatio',
  ActivityKillsDeathsAssists = 'ActivityKillsDeathsAssists',
  Deaths = 'Deaths',
  Kills = 'Kills',
  KillsDeathsRatio = 'KillsDeathsRatio',
  KillsDeathsAssists = 'KillsDeathsAssists',
  LbSingleGameKills = 'LbSingleGameKills',
  LbPrecisionKills = 'LbPrecisionKills',
  LbAssists = 'LbAssists',
  LbDeaths = 'LbDeaths',
  LbKills = 'LbKills',
  LbObjectivesCompleted = 'LbObjectivesCompleted',
  LbSingleGameScore = 'LbSingleGameScore',
  MaximumPowerLevel = 'MaximumPowerLevel',
  MedalAbilityDawnbladeAerial = 'MedalAbilityDawnbladeAerial',
  MedalAbilityDawnbladeSlam = 'MedalAbilityDawnbladeSlam',
  MedalAbilityFlowwalkerMulti = 'MedalAbilityFlowwalkerMulti',
  MedalAbilityFlowwalkerQuick = 'MedalAbilityFlowwalkerQuick',
  MedalAbilityGunslingerMulti = 'MedalAbilityGunslingerMulti',
  MedalAbilityGunslingerQuick = 'MedalAbilityGunslingerQuick',
  MedalAbilityJuggernautCombo = 'MedalAbilityJuggernautCombo',
  MedalAbilityJuggernautSlam = 'MedalAbilityJuggernautSlam',
  MedalAbilityNightstalkerLongRange = 'MedalAbilityNightstalkerLongRange',
  MedalAbilityNightstalkerTetherQuick = 'MedalAbilityNightstalkerTetherQuick',
  MedalAbilitySentinelCombo = 'MedalAbilitySentinelCombo',
  MedalAbilitySentinelWard = 'MedalAbilitySentinelWard',
  MedalAbilityStormcallerLandfall = 'MedalAbilityStormcallerLandfall',
  MedalAbilityStormcallerMulti = 'MedalAbilityStormcallerMulti',
  MedalAbilitySunbreakerLongRange = 'MedalAbilitySunbreakerLongRange',
  MedalAbilitySunbreakerMulti = 'MedalAbilitySunbreakerMulti',
  MedalAbilityVoidwalkerDistance = 'MedalAbilityVoidwalkerDistance',
  MedalAbilityVoidwalkerVortex = 'MedalAbilityVoidwalkerVortex',
  MedalAvenger = 'MedalAvenger',
  MedalControlAdvantageHold = 'MedalControlAdvantageHold',
  MedalControlAdvantageStreak = 'MedalControlAdvantageStreak',
  MedalControlCaptureAllZones = 'MedalControlCaptureAllZones',
  MedalControlMostAdvantage = 'MedalControlMostAdvantage',
  MedalControlPerimeterKill = 'MedalControlPerimeterKill',
  MedalControlPowerPlayWipe = 'MedalControlPowerPlayWipe',
  MedalCountdownDefense = 'MedalCountdownDefense',
  MedalCountdownDefusedLastStand = 'MedalCountdownDefusedLastStand',
  MedalCountdownDefusedMulti = 'MedalCountdownDefusedMulti',
  MedalCountdownDetonated = 'MedalCountdownDetonated',
  MedalCountdownPerfect = 'MedalCountdownPerfect',
  MedalCountdownRoundAllAlive = 'MedalCountdownRoundAllAlive',
  MedalCycle = 'MedalCycle',
  MedalDefeatHunterDodge = 'MedalDefeatHunterDodge',
  MedalDefeatTitanBrace = 'MedalDefeatTitanBrace',
  MedalDefeatWarlockSigil = 'MedalDefeatWarlockSigil',
  MedalDefense = 'MedalDefense',
  MedalMatchBlowout = 'MedalMatchBlowout',
  MedalMatchComeback = 'MedalMatchComeback',
  MedalMatchMostDamage = 'MedalMatchMostDamage',
  MedalMatchNeverTrailed = 'MedalMatchNeverTrailed',
  MedalMatchOvertime = 'MedalMatchOvertime',
  MedalMatchUndefeated = 'MedalMatchUndefeated',
  MedalMulti2x = 'MedalMulti2x',
  MedalMulti3x = 'MedalMulti3x',
  MedalMulti4x = 'MedalMulti4x',
  MedalMultiEntireTeam = 'MedalMultiEntireTeam',
  MedalPayback = 'MedalPayback',
  MedalQuickStrike = 'MedalQuickStrike',
  MedalStreak10x = 'MedalStreak10x',
  MedalStreak5x = 'MedalStreak5x',
  MedalStreakAbsurd = 'MedalStreakAbsurd',
  MedalStreakCombined = 'MedalStreakCombined',
  MedalStreakShutdown = 'MedalStreakShutdown',
  MedalStreakTeam = 'MedalStreakTeam',
  MedalSuperShutdown = 'MedalSuperShutdown',
  MedalSupremacyCrestCreditStreak = 'MedalSupremacyCrestCreditStreak',
  MedalSupremacyFirstCrest = 'MedalSupremacyFirstCrest',
  MedalSupremacyNeverCollected = 'MedalSupremacyNeverCollected',
  MedalSupremacyPerfectSecureRate = 'MedalSupremacyPerfectSecureRate',
  MedalSupremacyRecoverStreak = 'MedalSupremacyRecoverStreak',
  MedalSupremacySecureStreak = 'MedalSupremacySecureStreak',
  MedalSurvivalComeback = 'MedalSurvivalComeback',
  MedalSurvivalKnockout = 'MedalSurvivalKnockout',
  MedalSurvivalQuickWipe = 'MedalSurvivalQuickWipe',
  MedalSurvivalTeamUndefeated = 'MedalSurvivalTeamUndefeated',
  MedalSurvivalUndefeated = 'MedalSurvivalUndefeated',
  MedalSurvivalWinLastStand = 'MedalSurvivalWinLastStand',
  MedalWeaponAuto = 'MedalWeaponAuto',
  MedalWeaponFusion = 'MedalWeaponFusion',
  MedalWeaponGrenade = 'MedalWeaponGrenade',
  MedalWeaponHandCannon = 'MedalWeaponHandCannon',
  MedalWeaponPulse = 'MedalWeaponPulse',
  MedalWeaponRocket = 'MedalWeaponRocket',
  MedalWeaponScout = 'MedalWeaponScout',
  MedalWeaponShotgun = 'MedalWeaponShotgun',
  MedalWeaponSidearm = 'MedalWeaponSidearm',
  MedalWeaponSmg = 'MedalWeaponSmg',
  MedalWeaponSniper = 'MedalWeaponSniper',
  MedalWeaponSword = 'MedalWeaponSword',
  MedalsUnknown = 'MedalsUnknown',
  AllMedalsScore = 'AllMedalsScore',
  AllMedalsEarned = 'AllMedalsEarned',
  ObjectivesCompleted = 'ObjectivesCompleted',
  PrecisionKills = 'PrecisionKills',
  ResurrectionsPerformed = 'ResurrectionsPerformed',
  ResurrectionsReceived = 'ResurrectionsReceived',
  Score = 'Score',
  SecondsPlayed = 'SecondsPlayed',
  ActivityDurationSeconds = 'ActivityDurationSeconds',
  Standing = 'ActivityDurationSeconds',
  Suicides = 'Suicides',
  Team = 'Team',
  TotalDeathDistance = 'TotalDeathDistance',
  TotalKillDistance = 'TotalKillDistance',
  WeaponPrecisionKillsAutoRifle = 'WeaponPrecisionKillsAutoRifle',
  WeaponPrecisionKillsFusionRifle = 'WeaponPrecisionKillsFusionRifle',
  WeaponPrecisionKillsGrenade = 'WeaponPrecisionKillsGrenade',
  WeaponPrecisionKillsHandCannon = 'WeaponPrecisionKillsHandCannon',
  WeaponPrecisionKillsMachinegun = 'WeaponPrecisionKillsMachinegun',
  WeaponPrecisionKillsMelee = 'WeaponPrecisionKillsMelee',
  WeaponPrecisionKillsPulseRifle = 'WeaponPrecisionKillsPulseRifle',
  WeaponPrecisionKillsRocketLauncher = 'WeaponPrecisionKillsRocketLauncher',
  WeaponPrecisionKillsScoutRifle = 'WeaponPrecisionKillsScoutRifle',
  WeaponPrecisionKillsShotgun = 'WeaponPrecisionKillsShotgun',
  WeaponPrecisionKillsSniper = 'WeaponPrecisionKillsSniper',
  WeaponPrecisionKillsSubmachinegun = 'WeaponPrecisionKillsSubmachinegun',
  WeaponPrecisionKillsSuper = 'WeaponPrecisionKillsSuper',
  WeaponPrecisionKillsRelic = 'WeaponPrecisionKillsRelic',
  WeaponPrecisionKillsSideArm = 'WeaponPrecisionKillsSideArm',
  WeaponKillsAutoRifle = 'WeaponKillsAutoRifle',
  WeaponKillsFusionRifle = 'WeaponKillsFusionRifle',
  WeaponKillsGrenade = 'WeaponKillsGrenade',
  WeaponKillsHandCannon = 'WeaponKillsHandCannon',
  WeaponKillsMachinegun = 'WeaponKillsMachinegun',
  WeaponKillsMelee = 'WeaponKillsMelee',
  WeaponKillsPulseRifle = 'WeaponKillsPulseRifle',
  WeaponKillsRocketLauncher = 'WeaponKillsRocketLauncher',
  WeaponKillsScoutRifle = 'WeaponKillsScoutRifle',
  WeaponKillsShotgun = 'WeaponKillsShotgun',
  WeaponKillsSniper = 'WeaponKillsSniper',
  WeaponKillsSubmachinegun = 'WeaponKillsSubmachinegun',
  WeaponKillsSuper = 'WeaponKillsSuper',
  WeaponKillsRelic = 'WeaponKillsRelic',
  WeaponKillsSideArm = 'WeaponKillsSideArm',
  WeaponKillsSword = 'WeaponKillsSword',
  WeaponKillsAbility = 'WeaponKillsAbility',
  WeaponBestType = 'WeaponBestType',
  WeaponKillsPrecisionKillsAutoRifle = 'WeaponKillsPrecisionKillsAutoRifle',
  WeaponKillsPrecisionKillsFusionRifle = 'WeaponKillsPrecisionKillsFusionRifle',
  WeaponKillsPrecisionKillsGrenade = 'WeaponKillsPrecisionKillsGrenade',
  WeaponKillsPrecisionKillsHandCannon = 'WeaponKillsPrecisionKillsHandCannon',
  WeaponKillsPrecisionKillsMachinegun = 'WeaponKillsPrecisionKillsMachinegun',
  WeaponKillsPrecisionKillsMelee = 'WeaponKillsPrecisionKillsMelee',
  WeaponKillsPrecisionKillsPulseRifle = 'WeaponKillsPrecisionKillsPulseRifle',
  WeaponKillsPrecisionKillsRocketLauncher = 'WeaponKillsPrecisionKillsRocketLauncher',
  WeaponKillsPrecisionKillsScoutRifle = 'WeaponKillsPrecisionKillsScoutRifle',
  WeaponKillsPrecisionKillsShotgun = 'WeaponKillsPrecisionKillsShotgun',
  WeaponKillsPrecisionKillsSniper = 'WeaponKillsPrecisionKillsSniper',
  WeaponKillsPrecisionKillsSubmachinegun = 'WeaponKillsPrecisionKillsSubmachinegun',
  WeaponKillsPrecisionKillsSuper = 'WeaponKillsPrecisionKillsSuper',
  WeaponKillsPrecisionKillsRelic = 'WeaponKillsPrecisionKillsRelic',
  WeaponKillsPrecisionKillsSideArm = 'WeaponKillsPrecisionKillsSideArm',
  WinLossRatio = 'WinLossRatio',
  UniqueWeaponAssists = 'UniqueWeaponAssists',
  UniqueWeaponAssistDamage = 'UniqueWeaponAssistDamage',
  UniqueWeaponKills = 'UniqueWeaponKills',
  UniqueWeaponPrecisionKills = 'UniqueWeaponPrecisionKills',
  UniqueWeaponKillsPrecisionKills = 'UniqueWeaponKillsPrecisionKills',
  AllParticipantsCount = 'AllParticipantsCount',
  AllParticipantsScore = 'AllParticipantsScore',
  AllParticipantsTimePlayed = 'AllParticipantsTimePlayed',
  ActivityAssists = 'ActivityAssists',
  CompletionReason = 'CompletionReason',
  FireteamId = 'FireteamId',
  LongestKillSpree = 'LongestKillSpree',
  LongestSingleLife = 'LongestSingleLife',
  MostPrecisionKills = 'MostPrecisionKills',
  OrbsDropped = 'OrbsDropped',
  OrbsGathered = 'OrbsGathered',
  StartSeconds = 'StartSeconds',
  TimePlayedSeconds = 'TimePlayedSeconds',
  PlayerCount = 'PlayerCount',
  ActivityPrecisionKills = 'ActivityPrecisionKills',
  PublicEventsCompleted = 'PublicEventsCompleted',
  PublicEventsJoined = 'PublicEventsJoined',
  RemainingTimeAfterQuitSeconds = 'RemainingTimeAfterQuitSeconds',
  TeamScore = 'TeamScore',
  TotalActivityDurationSeconds = 'TotalActivityDurationSeconds',
  DailyMedalsEarned = 'DailyMedalsEarned',
  CombatRating = 'CombatRating',
  LbMostPrecisionKills = 'LbMostPrecisionKills',
  LbLongestKillSpree = 'LbLongestKillSpree',
  LbLongestKillDistance = 'LbLongestKillDistance',
  LbFastestCompletionMs = 'LbFastestCompletionMs',
  LbLongestSingleLife = 'LbLongestSingleLife',
  FastestCompletionMs = 'FastestCompletionMs',
  LongestKillDistance = 'LongestKillDistance',
  HighestCharacterLevel = 'HighestCharacterLevel',
  HighestLightLevel = 'HighestLightLevel',
  HighestSandboxLevel = 'HighestSandboxLevel',
  SparksCaptured = 'SparksCaptured',
  SlamDunks = 'SlamDunks',
  StyleDunks = 'StyleDunks',
  DunkKills = 'DunkKills',
  CarrierKills = 'CarrierKills',
  ActivityGatesHit = 'ActivityGatesHit',
  RaceCompletionSeconds = 'RaceCompletionSeconds',
  GatesHit = 'GatesHit',
  RaceCompletionMilliseconds = 'RaceCompletionMilliseconds',
}

/**
* Enum for different type definitions
* @enum
*/
export enum TypeDefinition {
  DestinyActivityGraphDefinition = 'DestinyActivityGraphDefinition',
  DestinyActivityModeDefinition = 'DestinyActivityModeDefinition',
  DestinyActivityModifierDefinition = 'DestinyActivityModifierDefinition',
  DestinyActivityTypeDefinition = 'DestinyActivityTypeDefinition',
  DestinyBondDefinition = 'DestinyBondDefinition',
  DestinyClassDefinition = 'DestinyClassDefinition',
  DestinyDamageTypeDefinition = 'DestinyDamageTypeDefinition',
  DestinyDestinationDefinition = 'DestinyDestinationDefinition',
  DestinyEnemyRaceDefinition = 'DestinyEnemyRaceDefinition',
  DestinyFactionDefinition = 'DestinyFactionDefinition',
  DestinyGenderDefinition = 'DestinyGenderDefinition',
  DestinyHistoricalStatsDefinition = 'DestinyHistoricalStatsDefinition',
  DestinyInventoryBucketDefinition = 'DestinyInventoryBucketDefinition',
  DestinyInventoryItemDefinition = 'DestinyInventoryItemDefinition',
  DestinyItemCategoryDefinition = 'DestinyItemCategoryDefinition',
  DestinyItemTierTypeDefinition = 'DestinyItemTierTypeDefinition',
  DestinyLocationDefinition = 'DestinyLocationDefinition',
  DestinyLoreDefinition = 'DestinyLoreDefinition',
  DestinyMedalTierDefinition = 'DestinyMedalTierDefinition',
  DestinyMilestoneDefinition = 'DestinyMilestoneDefinition',
  DestinyObjectiveDefinition = 'DestinyObjectiveDefinition',
  DestinyPlaceDefinition = 'DestinyPlaceDefinition',
  DestinyProgressionDefinition = 'DestinyProgressionDefinition',
  DestinyProgressionLevelRequirementDefinition = 'DestinyProgressionLevelRequirementDefinition',
  DestinyRaceDefinition = 'DestinyRaceDefinition',
  DestinyRewardSourceDefinition = 'DestinyRewardSourceDefinition',
  DestinySackRewardItemListDefinition = 'DestinySackRewardItemListDefinition',
  DestinySandboxPerkDefinition = 'DestinySandboxPerkDefinition',
  DestinySocketCategoryDefinition = 'DestinySocketCategoryDefinition',
  DestinySocketTypeDefinition = 'DestinySocketTypeDefinition',
  DestinyStatDefinition = 'DestinyStatDefinition',
  DestinyStatGroupDefinition = 'DestinyStatGroupDefinition',
  DestinyTalentGridDefinition = 'DestinyTalentGridDefinition',
  DestinyUnlockDefinition = 'DestinyUnlockDefinition',
  DestinyVendorCategoryDefinition = 'DestinyVendorCategoryDefinition',
  DestinyVendorDefinition = 'DestinyVendorDefinition',
}

/**
* Enum for the transfer status of an item
* @enum
*/
export enum TransferStatus {
  CanTransfer = 0,
  ItemIsEquipped = 1,
  NotTransferrable = 2,
  NoRoomInDestination = 4,
}

/**
* Enum for unit types
* @enum
*/
export enum UnitType {
  None = 0,
  Count = 1,
  PerGame = 2,
  Seconds = 3,
  Points = 4,
  Team = 5,
  Distance = 6,
  Percent = 7,
  Ratio = 8,
  Boolean = 9,
  WeaponType = 10,
  Standing = 11,
  Milliseconds = 12,
}

/**
* Enum for the vendor item refund policy
* @enum
*/
export enum VendorItemRefundPolicy {
  NotRefundable = 0,
  DeletesItem = 1,
  RevokesLicense = 2,
}

/**
* Enum for the vendor item status
* @enum
*/
export enum VendorItemStatus {
  Success = 0,
  NoInventorySpace = 1,
  NoFunds = 2,
  NoProgression = 4,
  NoUnlock = 8,
  NoQuantity = 16,
  OutsidePurchaseWindow = 32,
  NotAvailable = 64,
  UniquenessViolation = 128,
  UnknownError = 256,
  AlreadySelling = 512,
  Unsellable = 1024,
  SellingInhibited = 2048,
  AlreadyOwned = 4096,
}