// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'resultButton': string;
}
export const cssExports: CssExports;
export = cssExports;
