// This file is automatically generated.
// Please do not change this file!
export const date: string;
export const iconButton: string;
export const instructions: string;
export const searchHistory: string;
export const sorter: string;
export const tabs: string;
