// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteIcon': string;
  'highlightedItem': string;
  'invalid': string;
  'keyHelp': string;
  'menu': string;
  'menuItem': string;
  'menuItemHelp': string;
  'menuItemIcon': string;
  'menuItemQuery': string;
  'open': string;
  'openButton': string;
  'queryBody': string;
  'queryHeader': string;
  'saveSearchButton': string;
  'searchBar': string;
  'textHighlight': string;
}
export const cssExports: CssExports;
export default cssExports;
