// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'iconButton': string;
  'instructions': string;
  'searchHistory': string;
  'sorter': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
