// This file is automatically generated.
// Please do not change this file!
export const armoryItemIcon: string;
export const deleteIcon: string;
export const filterBarButton: string;
export const filterHelp: string;
export const highlightedItem: string;
export const invalid: string;
export const keyHelp: string;
export const menu: string;
export const menuItem: string;
export const menuItemIcon: string;
export const menuItemQuery: string;
export const namedQueryBody: string;
export const open: string;
export const openButton: string;
export const openInArmoryLabel: string;
export const saveSearchButton: string;
export const searchBar: string;
export const textHighlight: string;
