// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contents': string;
  'header': string;
  'searchResults': string;
}
export const cssExports: CssExports;
export = cssExports;
