// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bestStat': string;
  'classIcon': string;
  'comboCount': string;
  'dimmed': string;
  'factorCombo': string;
  'header': string;
  'headerDivider': string;
  'inlineBlock': string;
  'inlineIcon': string;
  'itemTriagePane': string;
  'junkIcon': string;
  'keepIcon': string;
  'keepMeter': string;
  'smaller': string;
  'statIconWrapper': string;
  'statValue': string;
  'tagIcon': string;
  'thisStat': string;
  'triageTable': string;
  'weaponSvg': string;
}
export const cssExports: CssExports;
export default cssExports;
