// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bestStat': string;
  'comboCount': string;
  'dimmed': string;
  'factorCombo': string;
  'header': string;
  'headerDivider': string;
  'headerImage': string;
  'inlineBlock': string;
  'inlineIcon': string;
  'itemTriagePane': string;
  'ownershipTable': string;
  'searchBarIcon': string;
  'smaller': string;
  'statIconWrapper': string;
  'statTable': string;
  'statValue': string;
  'thisStat': string;
  'weaponSvg': string;
}
export const cssExports: CssExports;
export default cssExports;
