// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artificeExplanation': string;
  'collapseTitle': string;
  'controls': string;
  'count': string;
  'dimmed': string;
  'factorCollapsedValue': string;
  'factorCombo': string;
  'factorIcon': string;
  'header': string;
  'headerDivider': string;
  'inLoadout': string;
  'inlineIcon': string;
  'itemTriagePane': string;
  'loadoutList': string;
  'loadoutName': string;
  'loadoutRow': string;
  'popupTabTitle': string;
  'similarItemsTable': string;
  'statTable': string;
  'statValue': string;
  'statsHeaderDivider': string;
  'statsHeaderLeft': string;
  'statsHeaderRight': string;
  'tableRow': string;
  'thumbsUp': string;
  'weaponSvg': string;
}
export const cssExports: CssExports;
export default cssExports;
