// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'factorIcon': string;
  'inlineIcon2': string;
  'modSlotIcon': string;
  'weaponSvg': string;
}
export const cssExports: CssExports;
export default cssExports;
