// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'junkIcon': string;
  'keepIcon': string;
  'tagIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
