// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonInfo': string;
  'buttonTitle': string;
  'failed': string;
  'iconList': string;
  'insertButton': string;
  'itemTypeIcon': string;
  'noSocketsMessage': string;
  'ok': string;
  'plug': string;
  'selectedButton': string;
  'selectedTitle': string;
  'socketKindButton': string;
  'stripSheet': string;
}
export const cssExports: CssExports;
export default cssExports;
