// This file is automatically generated.
// Please do not change this file!
export const buttonInfo: string;
export const buttonTitle: string;
export const failed: string;
export const iconList: string;
export const insertButton: string;
export const itemTypeIcon: string;
export const noSocketsMessage: string;
export const ok: string;
export const plug: string;
export const selectedButton: string;
export const selectedTitle: string;
export const socketKindButton: string;
export const stripSheet: string;
