// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cells': string;
  'debugPage': string;
  'error': string;
  'token': string;
}
export const cssExports: CssExports;
export default cssExports;
