// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'header': string;
  'logo': string;
  'social': string;
}
export const cssExports: CssExports;
export default cssExports;
