// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'hideButton': string;
}
export const cssExports: CssExports;
export = cssExports;
