// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorCode': string;
  'errorPanel': string;
  'links': string;
  'socials': string;
  'timeline': string;
}
export const cssExports: CssExports;
export = cssExports;
