// This file is automatically generated.
// Please do not change this file!
export const errorCode: string;
export const errorPanel: string;
export const links: string;
export const socials: string;
export const timeline: string;
