// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorCode': string;
  'errorPanel': string;
  'twitterLinks': string;
  'twitters': string;
}
export const cssExports: CssExports;
export default cssExports;
