// This file is automatically generated.
// Please do not change this file!
export const active: string;
export const beta: string;
export const container: string;
export const dev: string;
export const dropdown: string;
export const header: string;
export const headerLinks: string;
export const headerRight: string;
export const launchSeparateIcon: string;
export const logo: string;
export const logoLink: string;
export const menu: string;
export const menuItem: string;
export const pr: string;
export const pwaPrompt: string;
export const searchButton: string;
export const searchLink: string;
