// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'beta': string;
  'container': string;
  'dev': string;
  'dropdown': string;
  'dropdownEnter': string;
  'dropdownEnterActive': string;
  'dropdownExit': string;
  'dropdownExitActive': string;
  'header': string;
  'headerLinks': string;
  'headerRight': string;
  'launchSeparateIcon': string;
  'logo': string;
  'logoLink': string;
  'menu': string;
  'menuItem': string;
  'pwaPrompt': string;
  'searchButton': string;
  'searchLink': string;
}
export const cssExports: CssExports;
export default cssExports;
