// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badgeNew': string;
  'vendors': string;
}
export const cssExports: CssExports;
export default cssExports;
