// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'refreshButton': string;
  'userIsPlaying': string;
}
export const cssExports: CssExports;
export default cssExports;
