// This file is automatically generated.
// Please do not change this file!
export const errorDetails: string;
export const errorTooltip: string;
export const outOfDate: string;
export const refreshButton: string;
export const userIsPlaying: string;
