// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'content': string;
  'control': string;
  'errorDetails': string;
  'errorTooltip': string;
  'header': string;
  'minimalTooltip': string;
  'outOfDate': string;
  'refreshButton': string;
  'section': string;
  'tooltip': string;
  'userIsPlaying': string;
  'wideTooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
