// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appIcon': string;
  'hashtagTip': string;
  'loadoutRow': string;
  'menu': string;
  'menuButton': string;
  'menuButtons': string;
  'menuLoadout': string;
  'seasonHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
