// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'artifactMods': string;
  'classIcon': string;
  'contents': string;
  'fadeIn': string;
  'finding': string;
  'findings': string;
  'loadout': string;
  'loadoutNotes': string;
  'modsStack': string;
  'title': string;
}
export const cssExports: CssExports;
export = cssExports;
