// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'classIcon': string;
  'equipped': string;
  'itemCategory': string;
  'items': string;
  'loadout': string;
  'missingItems': string;
  'mods': string;
  'subClass': string;
  'unequipped': string;
}
export const cssExports: CssExports;
export default cssExports;
