// This file is automatically generated.
// Please do not change this file!
export const actions: string;
export const artifactMods: string;
export const classIcon: string;
export const contents: string;
export const fadeIn: string;
export const finding: string;
export const findings: string;
export const loadout: string;
export const loadoutNotes: string;
export const modsStack: string;
export const title: string;
