// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contents': string;
  'details': string;
  'error': string;
  'icon': string;
  'info': string;
  'inner': string;
  'notification': string;
  'progress': string;
  'success': string;
  'timer': string;
  'title': string;
  'trailer': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
