// This file is automatically generated.
// Please do not change this file!
export const contents: string;
export const details: string;
export const error: string;
export const icon: string;
export const info: string;
export const inner: string;
export const notification: string;
export const progress: string;
export const success: string;
export const timer: string;
export const title: string;
export const trailer: string;
export const warning: string;
