// This file is automatically generated.
// Please do not change this file!
export const invalidPlug: string;
export const notes: string;
export const orGroup: string;
export const roll: string;
export const rollGroup: string;
export const subtitle: string;
