// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'orGroup': string;
  'roll': string;
}
export const cssExports: CssExports;
export default cssExports;
