// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armory': string;
  'flavor': string;
  'header': string;
  'links': string;
  'roll': string;
  'source': string;
  'stats': string;
  'subtitle': string;
}
export const cssExports: CssExports;
export default cssExports;
