// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armory': string;
  'element': string;
  'flavor': string;
  'header': string;
  'headerContent': string;
  'season': string;
  'section': string;
  'source': string;
  'subtitle': string;
}
export const cssExports: CssExports;
export default cssExports;
