name: Notify Discord - i18n

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/locale/en.json'

jobs:
  post-i18n-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # needed to access HEAD^ for the previous version

      - name: Post i18n diff to Discord
        env:
          DISCORD_I18N_WEBHOOK: ${{ secrets.DISCORD_I18N_WEBHOOK }}
        run: python3 .github/scripts/i18n_discord.py
