// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bannerIcon': string;
  'icon': string;
  'metric': string;
  'metricIcon': string;
  'scopeIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
