// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'accountDetails': string;
  'auditLog': string;
  'first': string;
}
export const cssExports: CssExports;
export default cssExports;
