// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'character': string;
  'editor': string;
  'item': string;
  'powerLevel': string;
}
export const cssExports: CssExports;
export = cssExports;
