// This file is automatically generated.
// Please do not change this file!
export const classDropdownIcon: string;
export const classIcon: string;
export const classOption: string;
export const customDesc: string;
export const customStatEditor: string;
export const customStatView: string;
export const editableStatsRow: string;
export const filter: string;
export const headerRow: string;
export const identifyingInfo: string;
export const inputlike: string;
export const label: string;
export const pulseBorder: string;
export const statOption: string;
export const zero: string;
