// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classDropdownIcon': string;
  'classIcon': string;
  'classOption': string;
  'customDesc': string;
  'customStatEditor': string;
  'customStatView': string;
  'editableStatsRow': string;
  'filter': string;
  'headerRow': string;
  'identifyingInfo': string;
  'inputlike': string;
  'label': string;
  'pulseBorder': string;
  'statOption': string;
  'zero': string;
}
export const cssExports: CssExports;
export default cssExports;
