// This file is automatically generated.
// Please do not change this file!
export const autoTagTable: string;
export const fineprint: string;
export const horizontal: string;
export const itemSize: string;
export const newItem: string;
export const radioOptions: string;
export const setting: string;
export const settings: string;
