// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'disabled': string;
  'editor': string;
  'grabHandle': string;
  'grip': string;
  'item': string;
  'name': string;
  'sortForward': string;
  'sortReverse': string;
}
export const cssExports: CssExports;
export = cssExports;
