// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'disabled': string;
  'dragging': string;
  'editor': string;
  'grip': string;
  'item': string;
  'name': string;
  'sortForward': string;
  'sortReverse': string;
}
export const cssExports: CssExports;
export default cssExports;
