// This file is automatically generated.
// Please do not change this file!
export const button: string;
export const disabled: string;
export const editor: string;
export const grabHandle: string;
export const grip: string;
export const item: string;
export const name: string;
export const sortForward: string;
export const sortReverse: string;
