// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'text': string;
  'tooltipDiv': string;
}
export const cssExports: CssExports;
export = cssExports;
